package com.glens.pwCloudOs.pm.taskMgr.device.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class PmDeviceHealth implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.rowid
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;
    private String proName;
    private String categoryCode;
    private String categoryName;
    

	public String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.HEALTH_CODE
     *
     * @mbggenerated
     */
    private String healthCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.HEALTH_NAME
     *
     * @mbggenerated
     */
    private String healthName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private String sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private String sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private String sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_device_health.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.rowid
     *
     * @return the value of pm_device_health.rowid
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.rowid
     *
     * @param rowid the value for pm_device_health.rowid
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.COMPANY_CODE
     *
     * @return the value of pm_device_health.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.COMPANY_CODE
     *
     * @param companyCode the value for pm_device_health.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.PRO_NO
     *
     * @return the value of pm_device_health.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.PRO_NO
     *
     * @param proNo the value for pm_device_health.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.HEALTH_CODE
     *
     * @return the value of pm_device_health.HEALTH_CODE
     *
     * @mbggenerated
     */
    public String getHealthCode() {
        return healthCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.HEALTH_CODE
     *
     * @param healthCode the value for pm_device_health.HEALTH_CODE
     *
     * @mbggenerated
     */
    public void setHealthCode(String healthCode) {
        this.healthCode = healthCode == null ? null : healthCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.HEALTH_NAME
     *
     * @return the value of pm_device_health.HEALTH_NAME
     *
     * @mbggenerated
     */
    public String getHealthName() {
        return healthName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.HEALTH_NAME
     *
     * @param healthName the value for pm_device_health.HEALTH_NAME
     *
     * @mbggenerated
     */
    public void setHealthName(String healthName) {
        this.healthName = healthName == null ? null : healthName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.SYS_CREATE_TIME
     *
     * @return the value of pm_device_health.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public String getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for pm_device_health.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(String sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.SYS_UPDATE_TIME
     *
     * @return the value of pm_device_health.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for pm_device_health.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(String sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.SYS_DELETE_TIME
     *
     * @return the value of pm_device_health.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public String getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for pm_device_health.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(String sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.SYS_PROCESS_FLAG
     *
     * @return the value of pm_device_health.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for pm_device_health.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_device_health.REMARKS
     *
     * @return the value of pm_device_health.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_device_health.REMARKS
     *
     * @param remarks the value for pm_device_health.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}