package com.glens.pwCloudOs.pm.taskMgr.device.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class PmDeviceProblem implements ValueObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.rowid
	 * @mbggenerated
	 */
	private Long rowid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.COMPANY_CODE
	 * @mbggenerated
	 */
	private String companyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.PRO_NO
	 * @mbggenerated
	 */
	private String proNo;
	private String proName;
	
	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.PROBLEM_CODE
	 * @mbggenerated
	 */
	private String problemCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.PROBLEM_NAME
	 * @mbggenerated
	 */
	private String problemName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.PROBLEM_TYPE
	 * @mbggenerated
	 */
	private Integer problemType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.PARENT_PROBLEM_CODE
	 * @mbggenerated
	 */
	private String parentProblemCode;
	private String parentProblemName;
	
	public String getParentProblemName() {
		return parentProblemName;
	}

	public void setParentProblemName(String parentProblemName) {
		this.parentProblemName = parentProblemName;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.SYS_CREATE_TIME
	 * @mbggenerated
	 */
	private String sysCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.SYS_UPDATE_TIME
	 * @mbggenerated
	 */
	private String sysUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.SYS_DELETE_TIME
	 * @mbggenerated
	 */
	private String sysDeleteTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.SYS_PROCESS_FLAG
	 * @mbggenerated
	 */
	private String sysProcessFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pm_device_problem.REMARKS
	 * @mbggenerated
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.rowid
	 * @return  the value of pm_device_problem.rowid
	 * @mbggenerated
	 */
	public Long getRowid() {
		return rowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.rowid
	 * @param rowid  the value for pm_device_problem.rowid
	 * @mbggenerated
	 */
	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.COMPANY_CODE
	 * @return  the value of pm_device_problem.COMPANY_CODE
	 * @mbggenerated
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.COMPANY_CODE
	 * @param companyCode  the value for pm_device_problem.COMPANY_CODE
	 * @mbggenerated
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode == null ? null : companyCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.PRO_NO
	 * @return  the value of pm_device_problem.PRO_NO
	 * @mbggenerated
	 */
	public String getProNo() {
		return proNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.PRO_NO
	 * @param proNo  the value for pm_device_problem.PRO_NO
	 * @mbggenerated
	 */
	public void setProNo(String proNo) {
		this.proNo = proNo == null ? null : proNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.PROBLEM_CODE
	 * @return  the value of pm_device_problem.PROBLEM_CODE
	 * @mbggenerated
	 */
	public String getProblemCode() {
		return problemCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.PROBLEM_CODE
	 * @param problemCode  the value for pm_device_problem.PROBLEM_CODE
	 * @mbggenerated
	 */
	public void setProblemCode(String problemCode) {
		this.problemCode = problemCode == null ? null : problemCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.PROBLEM_NAME
	 * @return  the value of pm_device_problem.PROBLEM_NAME
	 * @mbggenerated
	 */
	public String getProblemName() {
		return problemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.PROBLEM_NAME
	 * @param problemName  the value for pm_device_problem.PROBLEM_NAME
	 * @mbggenerated
	 */
	public void setProblemName(String problemName) {
		this.problemName = problemName == null ? null : problemName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.PROBLEM_TYPE
	 * @return  the value of pm_device_problem.PROBLEM_TYPE
	 * @mbggenerated
	 */
	public Integer getProblemType() {
		return problemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.PROBLEM_TYPE
	 * @param problemType  the value for pm_device_problem.PROBLEM_TYPE
	 * @mbggenerated
	 */
	public void setProblemType(Integer problemType) {
		this.problemType = problemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.PARENT_PROBLEM_CODE
	 * @return  the value of pm_device_problem.PARENT_PROBLEM_CODE
	 * @mbggenerated
	 */
	public String getParentProblemCode() {
		return parentProblemCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.PARENT_PROBLEM_CODE
	 * @param parentProblemCode  the value for pm_device_problem.PARENT_PROBLEM_CODE
	 * @mbggenerated
	 */
	public void setParentProblemCode(String parentProblemCode) {
		this.parentProblemCode = parentProblemCode == null ? null
				: parentProblemCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.SYS_CREATE_TIME
	 * @return  the value of pm_device_problem.SYS_CREATE_TIME
	 * @mbggenerated
	 */
	public String getSysCreateTime() {
		return sysCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.SYS_CREATE_TIME
	 * @param sysCreateTime  the value for pm_device_problem.SYS_CREATE_TIME
	 * @mbggenerated
	 */
	public void setSysCreateTime(String sysCreateTime) {
		this.sysCreateTime = sysCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.SYS_UPDATE_TIME
	 * @return  the value of pm_device_problem.SYS_UPDATE_TIME
	 * @mbggenerated
	 */
	public String getSysUpdateTime() {
		return sysUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.SYS_UPDATE_TIME
	 * @param sysUpdateTime  the value for pm_device_problem.SYS_UPDATE_TIME
	 * @mbggenerated
	 */
	public void setSysUpdateTime(String sysUpdateTime) {
		this.sysUpdateTime = sysUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.SYS_DELETE_TIME
	 * @return  the value of pm_device_problem.SYS_DELETE_TIME
	 * @mbggenerated
	 */
	public String getSysDeleteTime() {
		return sysDeleteTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.SYS_DELETE_TIME
	 * @param sysDeleteTime  the value for pm_device_problem.SYS_DELETE_TIME
	 * @mbggenerated
	 */
	public void setSysDeleteTime(String sysDeleteTime) {
		this.sysDeleteTime = sysDeleteTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.SYS_PROCESS_FLAG
	 * @return  the value of pm_device_problem.SYS_PROCESS_FLAG
	 * @mbggenerated
	 */
	public String getSysProcessFlag() {
		return sysProcessFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.SYS_PROCESS_FLAG
	 * @param sysProcessFlag  the value for pm_device_problem.SYS_PROCESS_FLAG
	 * @mbggenerated
	 */
	public void setSysProcessFlag(String sysProcessFlag) {
		this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pm_device_problem.REMARKS
	 * @return  the value of pm_device_problem.REMARKS
	 * @mbggenerated
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pm_device_problem.REMARKS
	 * @param remarks  the value for pm_device_problem.REMARKS
	 * @mbggenerated
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}
}