package com.glens.pwCloudOs.pm.taskMgr.device.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class PowerDeviceBaseAttrField implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.rowid
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.DEVICE_TYPE_CODE
     *
     * @mbggenerated
     */
    private String deviceTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.E_NAME
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.C_NAME
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.IS_PK
     *
     * @mbggenerated
     */
    private Integer isPk;
    private Integer isNotNull;
    private Integer isFeature;
    

    public Integer getIsFeature() {
		return isFeature;
	}

	public void setIsFeature(Integer isFeature) {
		this.isFeature = isFeature;
	}

	public Integer getIsNotNull() {
		return isNotNull;
	}

	public void setIsNotNull(Integer isNotNull) {
		this.isNotNull = isNotNull;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.D_TYPE
     *
     * @mbggenerated
     */
    private Integer dtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.ENUM_SOURCE
     *
     * @mbggenerated
     */
    private Integer enumSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.DIM_SEARCH
     *
     * @mbggenerated
     */
    private Integer dimList;
    
    public Integer getDimList() {
		return dimList;
	}

	public void setDimList(Integer dimList) {
		this.dimList = dimList;
	}

	private Integer dimSearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.DIM_MAPRENDER
     *
     * @mbggenerated
     */
    private Integer dimMaprender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.DIM_ORDER
     *
     * @mbggenerated
     */
    private Integer dimOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private Date sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_base_attr_field.ENUM_VALUE
     *
     * @mbggenerated
     */
    private String enumValue;
    
    private String proName;
    private String deviceTypeName;
    private String categoryCode;
    private String categoryName;
    
    
    public String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getDeviceTypeName() {
		return deviceTypeName;
	}

	public void setDeviceTypeName(String deviceTypeName) {
		this.deviceTypeName = deviceTypeName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.rowid
     *
     * @return the value of power_device_base_attr_field.rowid
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.rowid
     *
     * @param rowid the value for power_device_base_attr_field.rowid
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.COMPANY_CODE
     *
     * @return the value of power_device_base_attr_field.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.COMPANY_CODE
     *
     * @param companyCode the value for power_device_base_attr_field.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.PRO_NO
     *
     * @return the value of power_device_base_attr_field.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.PRO_NO
     *
     * @param proNo the value for power_device_base_attr_field.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.DEVICE_TYPE_CODE
     *
     * @return the value of power_device_base_attr_field.DEVICE_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getDeviceTypeCode() {
        return deviceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.DEVICE_TYPE_CODE
     *
     * @param deviceTypeCode the value for power_device_base_attr_field.DEVICE_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setDeviceTypeCode(String deviceTypeCode) {
        this.deviceTypeCode = deviceTypeCode == null ? null : deviceTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.E_NAME
     *
     * @return the value of power_device_base_attr_field.E_NAME
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.E_NAME
     *
     * @param eName the value for power_device_base_attr_field.E_NAME
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.C_NAME
     *
     * @return the value of power_device_base_attr_field.C_NAME
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.C_NAME
     *
     * @param cName the value for power_device_base_attr_field.C_NAME
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.IS_PK
     *
     * @return the value of power_device_base_attr_field.IS_PK
     *
     * @mbggenerated
     */
    public Integer getIsPk() {
        return isPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.IS_PK
     *
     * @param isPk the value for power_device_base_attr_field.IS_PK
     *
     * @mbggenerated
     */
    public void setIsPk(Integer isPk) {
        this.isPk = isPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.D_TYPE
     *
     * @return the value of power_device_base_attr_field.D_TYPE
     *
     * @mbggenerated
     */
    public Integer getDtype() {
        return dtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.D_TYPE
     *
     * @param dType the value for power_device_base_attr_field.D_TYPE
     *
     * @mbggenerated
     */
    public void setDtype(Integer dtype) {
        this.dtype = dtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.ENUM_SOURCE
     *
     * @return the value of power_device_base_attr_field.ENUM_SOURCE
     *
     * @mbggenerated
     */
    public Integer getEnumSource() {
        return enumSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.ENUM_SOURCE
     *
     * @param enumSource the value for power_device_base_attr_field.ENUM_SOURCE
     *
     * @mbggenerated
     */
    public void setEnumSource(Integer enumSource) {
        this.enumSource = enumSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.DIM_SEARCH
     *
     * @return the value of power_device_base_attr_field.DIM_SEARCH
     *
     * @mbggenerated
     */
    public Integer getDimSearch() {
        return dimSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.DIM_SEARCH
     *
     * @param dimSearch the value for power_device_base_attr_field.DIM_SEARCH
     *
     * @mbggenerated
     */
    public void setDimSearch(Integer dimSearch) {
        this.dimSearch = dimSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.DIM_MAPRENDER
     *
     * @return the value of power_device_base_attr_field.DIM_MAPRENDER
     *
     * @mbggenerated
     */
    public Integer getDimMaprender() {
        return dimMaprender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.DIM_MAPRENDER
     *
     * @param dimMaprender the value for power_device_base_attr_field.DIM_MAPRENDER
     *
     * @mbggenerated
     */
    public void setDimMaprender(Integer dimMaprender) {
        this.dimMaprender = dimMaprender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.DIM_ORDER
     *
     * @return the value of power_device_base_attr_field.DIM_ORDER
     *
     * @mbggenerated
     */
    public Integer getDimOrder() {
        return dimOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.DIM_ORDER
     *
     * @param dimOrder the value for power_device_base_attr_field.DIM_ORDER
     *
     * @mbggenerated
     */
    public void setDimOrder(Integer dimOrder) {
        this.dimOrder = dimOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.SYS_CREATE_TIME
     *
     * @return the value of power_device_base_attr_field.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for power_device_base_attr_field.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(Date sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.SYS_UPDATE_TIME
     *
     * @return the value of power_device_base_attr_field.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for power_device_base_attr_field.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(Date sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.SYS_DELETE_TIME
     *
     * @return the value of power_device_base_attr_field.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for power_device_base_attr_field.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(Date sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.SYS_PROCESS_FLAG
     *
     * @return the value of power_device_base_attr_field.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for power_device_base_attr_field.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.REMARKS
     *
     * @return the value of power_device_base_attr_field.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.REMARKS
     *
     * @param remarks the value for power_device_base_attr_field.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_base_attr_field.ENUM_VALUE
     *
     * @return the value of power_device_base_attr_field.ENUM_VALUE
     *
     * @mbggenerated
     */
    public String getEnumValue() {
        return enumValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_base_attr_field.ENUM_VALUE
     *
     * @param enumValue the value for power_device_base_attr_field.ENUM_VALUE
     *
     * @mbggenerated
     */
    public void setEnumValue(String enumValue) {
        this.enumValue = enumValue == null ? null : enumValue.trim();
    }
}