package com.glens.pwCloudOs.materielMg.assetMg.asset.vo;

import com.glens.eap.platform.core.beans.ValueObject;

public class AssetVo implements ValueObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.ASSET_QR_CODE
	 * 
	 * @mbggenerated
	 */
	private String assetQrCode;
	private Long rowno;

	public Long getRowno() {
		return rowno;
	}

	public void setRowno(Long rowno) {
		this.rowno = rowno;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.ASSET_CODE
	 * 
	 * @mbggenerated
	 */
	private String assetCode;

	private String assetName;
	private String statusname;

	public String getStatusname() {
		return statusname;
	}

	public void setStatusname(String statusname) {
		this.statusname = statusname;
	}

	private String vaEngineNo;

	private String vaCarframeNo;

	private String brand;
	private String modelNo;
	private String forms;
	private int count;

	private String isMark;

	private String markDate;

	private String markOwner;

	private String stockPeriod;

	private String stockPeriodName;

	public String getIsMark() {
		return isMark;
	}

	public void setIsMark(String isMark) {
		this.isMark = isMark;
	}

	public String getMarkDate() {
		return markDate;
	}

	public void setMarkDate(String markDate) {
		this.markDate = markDate;
	}

	public String getMarkOwner() {
		return markOwner;
	}

	public void setMarkOwner(String markOwner) {
		this.markOwner = markOwner;
	}

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModelNo() {
		return modelNo;
	}

	public void setModelNo(String modelNo) {
		this.modelNo = modelNo;
	}

	public String getForms() {
		return forms;
	}

	public void setForms(String forms) {
		this.forms = forms;
	}

	public String getVaEngineNo() {
		return vaEngineNo;
	}

	public void setVaEngineNo(String vaEngineNo) {
		this.vaEngineNo = vaEngineNo;
	}

	public String getVaCarframeNo() {
		return vaCarframeNo;
	}

	public void setVaCarframeNo(String vaCarframeNo) {
		this.vaCarframeNo = vaCarframeNo;
	}

	public String getAssetName() {
		return assetName;
	}

	public void setAssetName(String assetName) {
		this.assetName = assetName;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.ASSET_TYPE_CODE
	 * 
	 * @mbggenerated
	 */
	private String assetTypeCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.PRICE1
	 * 
	 * @mbggenerated
	 */
	private Float price1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.PRICE2
	 * 
	 * @mbggenerated
	 */
	private Float price2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.BILL
	 * 
	 * @mbggenerated
	 */
	private String bill;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.DATE_PURCHASE
	 * 
	 * @mbggenerated
	 */
	private String datePurchase;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.DATE_STORAGE
	 * 
	 * @mbggenerated
	 */
	private String dateStorage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.DATE_DUMP
	 * 
	 * @mbggenerated
	 */
	private String dateDump;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.DUMP_AMOUNT
	 * 
	 * @mbggenerated
	 */
	private Float dumpAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.STATUS
	 * 
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.LOAN_EMPLOYEECODE
	 * 
	 * @mbggenerated
	 */
	private String loanEmployeecode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.LOAN_EMPLOYEENAME
	 * 
	 * @mbggenerated
	 */
	private String loanEmployeename;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.LOAN_UNIT_CODE
	 * 
	 * @mbggenerated
	 */
	private String loanUnitCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.LOAN_UNIT_NAME
	 * 
	 * @mbggenerated
	 */
	private String loanUnitName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.LOAN_PRO_NO
	 * 
	 * @mbggenerated
	 */
	private String loanProNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.LOAN_PRO_NAME
	 * 
	 * @mbggenerated
	 */
	private String loanProName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.LOCATION
	 * 
	 * @mbggenerated
	 */
	private String location;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.VA_NO
	 * 
	 * @mbggenerated
	 */
	private String vaNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.VA_OIL
	 * 
	 * @mbggenerated
	 */
	private Integer vaOil;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.VA_OIL_CONSUMPTION
	 * 
	 * @mbggenerated
	 */
	private Float vaOilConsumption;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.VA_INIT_MILEAGE
	 * 
	 * @mbggenerated
	 */
	private Integer vaInitMileage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column gm_asset_base.REMARKS
	 * 
	 * @mbggenerated
	 */
	private String remarks;

	private String assetDesc;

	private String assetClassName;

	private String assetTypeName;

	private Integer assetMark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.ASSET_QR_CODE
	 * 
	 * @return the value of gm_asset_base.ASSET_QR_CODE
	 * 
	 * @mbggenerated
	 */
	public String getAssetQrCode() {
		return assetQrCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.ASSET_QR_CODE
	 * 
	 * @param assetQrCode
	 *            the value for gm_asset_base.ASSET_QR_CODE
	 * 
	 * @mbggenerated
	 */
	public void setAssetQrCode(String assetQrCode) {
		this.assetQrCode = assetQrCode == null ? null : assetQrCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.ASSET_CODE
	 * 
	 * @return the value of gm_asset_base.ASSET_CODE
	 * 
	 * @mbggenerated
	 */
	public String getAssetCode() {
		return assetCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.ASSET_CODE
	 * 
	 * @param assetCode
	 *            the value for gm_asset_base.ASSET_CODE
	 * 
	 * @mbggenerated
	 */
	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode == null ? null : assetCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.ASSET_TYPE_CODE
	 * 
	 * @return the value of gm_asset_base.ASSET_TYPE_CODE
	 * 
	 * @mbggenerated
	 */
	public String getAssetTypeCode() {
		return assetTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.ASSET_TYPE_CODE
	 * 
	 * @param assetTypeCode
	 *            the value for gm_asset_base.ASSET_TYPE_CODE
	 * 
	 * @mbggenerated
	 */
	public void setAssetTypeCode(String assetTypeCode) {
		this.assetTypeCode = assetTypeCode == null ? null : assetTypeCode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.PRICE1
	 * 
	 * @return the value of gm_asset_base.PRICE1
	 * 
	 * @mbggenerated
	 */
	public Float getPrice1() {
		return price1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.PRICE1
	 * 
	 * @param price1
	 *            the value for gm_asset_base.PRICE1
	 * 
	 * @mbggenerated
	 */
	public void setPrice1(Float price1) {
		this.price1 = price1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.PRICE2
	 * 
	 * @return the value of gm_asset_base.PRICE2
	 * 
	 * @mbggenerated
	 */
	public Float getPrice2() {
		return price2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.PRICE2
	 * 
	 * @param price2
	 *            the value for gm_asset_base.PRICE2
	 * 
	 * @mbggenerated
	 */
	public void setPrice2(Float price2) {
		this.price2 = price2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.BILL
	 * 
	 * @return the value of gm_asset_base.BILL
	 * 
	 * @mbggenerated
	 */
	public String getBill() {
		return bill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.BILL
	 * 
	 * @param bill
	 *            the value for gm_asset_base.BILL
	 * 
	 * @mbggenerated
	 */
	public void setBill(String bill) {
		this.bill = bill == null ? null : bill.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.DATE_PURCHASE
	 * 
	 * @return the value of gm_asset_base.DATE_PURCHASE
	 * 
	 * @mbggenerated
	 */
	public String getDatePurchase() {
		return datePurchase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.DATE_PURCHASE
	 * 
	 * @param datePurchase
	 *            the value for gm_asset_base.DATE_PURCHASE
	 * 
	 * @mbggenerated
	 */
	public void setDatePurchase(String datePurchase) {
		this.datePurchase = datePurchase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.DATE_STORAGE
	 * 
	 * @return the value of gm_asset_base.DATE_STORAGE
	 * 
	 * @mbggenerated
	 */
	public String getDateStorage() {
		return dateStorage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.DATE_STORAGE
	 * 
	 * @param dateStorage
	 *            the value for gm_asset_base.DATE_STORAGE
	 * 
	 * @mbggenerated
	 */
	public void setDateStorage(String dateStorage) {
		this.dateStorage = dateStorage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.DATE_DUMP
	 * 
	 * @return the value of gm_asset_base.DATE_DUMP
	 * 
	 * @mbggenerated
	 */
	public String getDateDump() {
		return dateDump;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.DATE_DUMP
	 * 
	 * @param dateDump
	 *            the value for gm_asset_base.DATE_DUMP
	 * 
	 * @mbggenerated
	 */
	public void setDateDump(String dateDump) {
		this.dateDump = dateDump;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.DUMP_AMOUNT
	 * 
	 * @return the value of gm_asset_base.DUMP_AMOUNT
	 * 
	 * @mbggenerated
	 */
	public Float getDumpAmount() {
		return dumpAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.DUMP_AMOUNT
	 * 
	 * @param dumpAmount
	 *            the value for gm_asset_base.DUMP_AMOUNT
	 * 
	 * @mbggenerated
	 */
	public void setDumpAmount(Float dumpAmount) {
		this.dumpAmount = dumpAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.STATUS
	 * 
	 * @return the value of gm_asset_base.STATUS
	 * 
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.STATUS
	 * 
	 * @param status
	 *            the value for gm_asset_base.STATUS
	 * 
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.LOAN_EMPLOYEECODE
	 * 
	 * @return the value of gm_asset_base.LOAN_EMPLOYEECODE
	 * 
	 * @mbggenerated
	 */
	public String getLoanEmployeecode() {
		return loanEmployeecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.LOAN_EMPLOYEECODE
	 * 
	 * @param loanEmployeecode
	 *            the value for gm_asset_base.LOAN_EMPLOYEECODE
	 * 
	 * @mbggenerated
	 */
	public void setLoanEmployeecode(String loanEmployeecode) {
		this.loanEmployeecode = loanEmployeecode == null ? null
				: loanEmployeecode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.LOAN_EMPLOYEENAME
	 * 
	 * @return the value of gm_asset_base.LOAN_EMPLOYEENAME
	 * 
	 * @mbggenerated
	 */
	public String getLoanEmployeename() {
		return loanEmployeename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.LOAN_EMPLOYEENAME
	 * 
	 * @param loanEmployeename
	 *            the value for gm_asset_base.LOAN_EMPLOYEENAME
	 * 
	 * @mbggenerated
	 */
	public void setLoanEmployeename(String loanEmployeename) {
		this.loanEmployeename = loanEmployeename == null ? null
				: loanEmployeename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.LOAN_UNIT_CODE
	 * 
	 * @return the value of gm_asset_base.LOAN_UNIT_CODE
	 * 
	 * @mbggenerated
	 */
	public String getLoanUnitCode() {
		return loanUnitCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.LOAN_UNIT_CODE
	 * 
	 * @param loanUnitCode
	 *            the value for gm_asset_base.LOAN_UNIT_CODE
	 * 
	 * @mbggenerated
	 */
	public void setLoanUnitCode(String loanUnitCode) {
		this.loanUnitCode = loanUnitCode == null ? null : loanUnitCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.LOAN_UNIT_NAME
	 * 
	 * @return the value of gm_asset_base.LOAN_UNIT_NAME
	 * 
	 * @mbggenerated
	 */
	public String getLoanUnitName() {
		return loanUnitName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.LOAN_UNIT_NAME
	 * 
	 * @param loanUnitName
	 *            the value for gm_asset_base.LOAN_UNIT_NAME
	 * 
	 * @mbggenerated
	 */
	public void setLoanUnitName(String loanUnitName) {
		this.loanUnitName = loanUnitName == null ? null : loanUnitName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.LOAN_PRO_NO
	 * 
	 * @return the value of gm_asset_base.LOAN_PRO_NO
	 * 
	 * @mbggenerated
	 */
	public String getLoanProNo() {
		return loanProNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.LOAN_PRO_NO
	 * 
	 * @param loanProNo
	 *            the value for gm_asset_base.LOAN_PRO_NO
	 * 
	 * @mbggenerated
	 */
	public void setLoanProNo(String loanProNo) {
		this.loanProNo = loanProNo == null ? null : loanProNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.LOAN_PRO_NAME
	 * 
	 * @return the value of gm_asset_base.LOAN_PRO_NAME
	 * 
	 * @mbggenerated
	 */
	public String getLoanProName() {
		return loanProName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.LOAN_PRO_NAME
	 * 
	 * @param loanProName
	 *            the value for gm_asset_base.LOAN_PRO_NAME
	 * 
	 * @mbggenerated
	 */
	public void setLoanProName(String loanProName) {
		this.loanProName = loanProName == null ? null : loanProName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.LOCATION
	 * 
	 * @return the value of gm_asset_base.LOCATION
	 * 
	 * @mbggenerated
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.LOCATION
	 * 
	 * @param location
	 *            the value for gm_asset_base.LOCATION
	 * 
	 * @mbggenerated
	 */
	public void setLocation(String location) {
		this.location = location == null ? null : location.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.VA_NO
	 * 
	 * @return the value of gm_asset_base.VA_NO
	 * 
	 * @mbggenerated
	 */
	public String getVaNo() {
		return vaNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.VA_NO
	 * 
	 * @param vaNo
	 *            the value for gm_asset_base.VA_NO
	 * 
	 * @mbggenerated
	 */
	public void setVaNo(String vaNo) {
		this.vaNo = vaNo == null ? null : vaNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.VA_OIL
	 * 
	 * @return the value of gm_asset_base.VA_OIL
	 * 
	 * @mbggenerated
	 */
	public Integer getVaOil() {
		return vaOil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.VA_OIL
	 * 
	 * @param vaOil
	 *            the value for gm_asset_base.VA_OIL
	 * 
	 * @mbggenerated
	 */
	public void setVaOil(Integer vaOil) {
		this.vaOil = vaOil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.VA_OIL_CONSUMPTION
	 * 
	 * @return the value of gm_asset_base.VA_OIL_CONSUMPTION
	 * 
	 * @mbggenerated
	 */
	public Float getVaOilConsumption() {
		return vaOilConsumption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.VA_OIL_CONSUMPTION
	 * 
	 * @param vaOilConsumption
	 *            the value for gm_asset_base.VA_OIL_CONSUMPTION
	 * 
	 * @mbggenerated
	 */
	public void setVaOilConsumption(Float vaOilConsumption) {
		this.vaOilConsumption = vaOilConsumption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.VA_INIT_MILEAGE
	 * 
	 * @return the value of gm_asset_base.VA_INIT_MILEAGE
	 * 
	 * @mbggenerated
	 */
	public Integer getVaInitMileage() {
		return vaInitMileage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.VA_INIT_MILEAGE
	 * 
	 * @param vaInitMileage
	 *            the value for gm_asset_base.VA_INIT_MILEAGE
	 * 
	 * @mbggenerated
	 */
	public void setVaInitMileage(Integer vaInitMileage) {
		this.vaInitMileage = vaInitMileage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column gm_asset_base.REMARKS
	 * 
	 * @return the value of gm_asset_base.REMARKS
	 * 
	 * @mbggenerated
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column gm_asset_base.REMARKS
	 * 
	 * @param remarks
	 *            the value for gm_asset_base.REMARKS
	 * 
	 * @mbggenerated
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	public String getAssetDesc() {
		return assetDesc;
	}

	public void setAssetDesc(String assetDesc) {
		this.assetDesc = assetDesc;
	}

	public String getAssetClassName() {
		return assetClassName;
	}

	public void setAssetClassName(String assetClassName) {
		this.assetClassName = assetClassName;
	}

	public String getAssetTypeName() {
		return assetTypeName;
	}

	public void setAssetTypeName(String assetTypeName) {
		this.assetTypeName = assetTypeName;
	}

	public Integer getAssetMark() {
		return assetMark;
	}

	public void setAssetMark(Integer assetMark) {
		this.assetMark = assetMark;
	}

	public String getStockPeriod() {
		return stockPeriod;
	}

	public void setStockPeriod(String stockPeriod) {
		this.stockPeriod = stockPeriod;
	}

	public String getStockPeriodName() {
		return stockPeriodName;
	}

	public void setStockPeriodName(String stockPeriodName) {
		this.stockPeriodName = stockPeriodName;
	}

	
}