package com.glens.pwCloudOs.pe.boxCheck.web;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.web.multipart.MultipartFile;

import com.glens.eap.platform.core.web.ControllerForm;

public class PeBcBoxMeterRelCheckForm extends ControllerForm {
	private MultipartFile excelFile;
	
	public MultipartFile getExcelFile() {
		return excelFile;
	}

	public void setExcelFile(MultipartFile excelFile) {
		this.excelFile = excelFile;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_bc_box_meter_rel_check.ROWID
	 * @mbggenerated
	 */
	private Long rowid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_bc_box_meter_rel_check.BOX_CODE
	 * @mbggenerated
	 */
	private String boxCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_bc_box_meter_rel_check.METER_CODE
	 * @mbggenerated
	 */
	private String meterCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_bc_box_meter_rel_check.TRANS_SVS_AREA_CODE
	 * @mbggenerated
	 */
	private String transSvsAreaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_bc_box_meter_rel_check.CHECK_RESULT
	 * @mbggenerated
	 */
	private Integer checkResult;
	private String checkResultName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_bc_box_meter_rel_check.CHECK_TIME
	 * @mbggenerated
	 */
	private String checkTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pe_bc_box_meter_rel_check.CHECK_USER
	 * @mbggenerated
	 */
	private String checkUser;
	private String checkUserName;
	
	private int isNew;
	
	private String companyCode;
	private String proNo;
	private String proName;
	private String mctCode;
	private String deviceObjCode;
	private String deviceObjName;
	
	
	public String getCheckResultName() {
		return checkResultName;
	}

	public void setCheckResultName(String checkResultName) {
		this.checkResultName = checkResultName;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getCompanyCode() {
		return companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getProNo() {
		return proNo;
	}

	public void setProNo(String proNo) {
		this.proNo = proNo;
	}

	public String getMctCode() {
		return mctCode;
	}

	public void setMctCode(String mctCode) {
		this.mctCode = mctCode;
	}

	public String getDeviceObjCode() {
		return deviceObjCode;
	}

	public void setDeviceObjCode(String deviceObjCode) {
		this.deviceObjCode = deviceObjCode;
	}

	public String getDeviceObjName() {
		return deviceObjName;
	}

	public void setDeviceObjName(String deviceObjName) {
		this.deviceObjName = deviceObjName;
	}

	public int getIsNew() {
		return isNew;
	}

	public void setIsNew(int isNew) {
		this.isNew = isNew;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_bc_box_meter_rel_check.ROWID
	 * @return  the value of pe_bc_box_meter_rel_check.ROWID
	 * @mbggenerated
	 */
	public Long getRowid() {
		return rowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_bc_box_meter_rel_check.ROWID
	 * @param rowid  the value for pe_bc_box_meter_rel_check.ROWID
	 * @mbggenerated
	 */
	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_bc_box_meter_rel_check.BOX_CODE
	 * @return  the value of pe_bc_box_meter_rel_check.BOX_CODE
	 * @mbggenerated
	 */
	public String getBoxCode() {
		return boxCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_bc_box_meter_rel_check.BOX_CODE
	 * @param boxCode  the value for pe_bc_box_meter_rel_check.BOX_CODE
	 * @mbggenerated
	 */
	public void setBoxCode(String boxCode) {
		this.boxCode = boxCode == null ? null : boxCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_bc_box_meter_rel_check.METER_CODE
	 * @return  the value of pe_bc_box_meter_rel_check.METER_CODE
	 * @mbggenerated
	 */
	public String getMeterCode() {
		return meterCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_bc_box_meter_rel_check.METER_CODE
	 * @param meterCode  the value for pe_bc_box_meter_rel_check.METER_CODE
	 * @mbggenerated
	 */
	public void setMeterCode(String meterCode) {
		this.meterCode = meterCode == null ? null : meterCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_bc_box_meter_rel_check.TRANS_SVS_AREA_CODE
	 * @return  the value of pe_bc_box_meter_rel_check.TRANS_SVS_AREA_CODE
	 * @mbggenerated
	 */
	public String getTransSvsAreaCode() {
		return transSvsAreaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_bc_box_meter_rel_check.TRANS_SVS_AREA_CODE
	 * @param transSvsAreaCode  the value for pe_bc_box_meter_rel_check.TRANS_SVS_AREA_CODE
	 * @mbggenerated
	 */
	public void setTransSvsAreaCode(String transSvsAreaCode) {
		this.transSvsAreaCode = transSvsAreaCode == null ? null
				: transSvsAreaCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_bc_box_meter_rel_check.CHECK_RESULT
	 * @return  the value of pe_bc_box_meter_rel_check.CHECK_RESULT
	 * @mbggenerated
	 */
	public Integer getCheckResult() {
		return checkResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_bc_box_meter_rel_check.CHECK_RESULT
	 * @param checkResult  the value for pe_bc_box_meter_rel_check.CHECK_RESULT
	 * @mbggenerated
	 */
	public void setCheckResult(Integer checkResult) {
		this.checkResult = checkResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_bc_box_meter_rel_check.CHECK_TIME
	 * @return  the value of pe_bc_box_meter_rel_check.CHECK_TIME
	 * @mbggenerated
	 */
	public String getCheckTime() {
		return checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_bc_box_meter_rel_check.CHECK_TIME
	 * @param checkTime  the value for pe_bc_box_meter_rel_check.CHECK_TIME
	 * @mbggenerated
	 */
	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pe_bc_box_meter_rel_check.CHECK_USER
	 * @return  the value of pe_bc_box_meter_rel_check.CHECK_USER
	 * @mbggenerated
	 */
	public String getCheckUser() {
		return checkUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pe_bc_box_meter_rel_check.CHECK_USER
	 * @param checkUser  the value for pe_bc_box_meter_rel_check.CHECK_USER
	 * @mbggenerated
	 */
	public void setCheckUser(String checkUser) {
		this.checkUser = checkUser == null ? null : checkUser.trim();
	}
	
	public String getCheckUserName() {
		return checkUserName;
	}

	public void setCheckUserName(String checkUserName) {
		this.checkUserName = checkUserName;
	}

	@Override
	protected Map doPreToMap() {
		Map map = new HashMap();
		return map;
	}

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub
		return null;
	}

}
