package com.glens.pwCloudOs.pm.everydayMgr.assetsMgr.web;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import com.glens.eap.platform.core.annotation.ValueObjectProcessor;
import com.glens.eap.platform.core.web.ControllerForm;
@ValueObjectProcessor(clazz = "com.glens.pwCloudOs.pm.everydayMgr.assetsMgr.vo.GmAssetRentVo")
public class GmAssetRentForm extends ControllerForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.rowid
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.ASSET_CODE
     *
     * @mbggenerated
     */
    private String assetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.LOAN_EMPLOYEECODE
     *
     * @mbggenerated
     */
    private String loanEmployeecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.LOAN_EMPLOYEENAME
     *
     * @mbggenerated
     */
    private String loanEmployeename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.LOAN_UNIT_CODE
     *
     * @mbggenerated
     */
    private String loanUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.LOAN_UNIT_NAME
     *
     * @mbggenerated
     */
    private String loanUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.LOAN_PRO_NO
     *
     * @mbggenerated
     */
    private String loanProNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.LOAN_PRO_NAME
     *
     * @mbggenerated
     */
    private String loanProName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.RENT_DATE
     *
     * @mbggenerated
     */
    private String rentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.ESTIMATE_RETURN_DATE
     *
     * @mbggenerated
     */
    private String estimateReturnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.RETURN_DATE
     *
     * @mbggenerated
     */
    private String returnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.RENT_STATUS
     *
     * @mbggenerated
     */
    private Integer rentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.FLOW_STATUS
     *
     * @mbggenerated
     */
    private Integer flowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private String sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private String sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private String sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_rent.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.rowid
     *
     * @return the value of gm_asset_rent.rowid
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.rowid
     *
     * @param rowid the value for gm_asset_rent.rowid
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.ASSET_CODE
     *
     * @return the value of gm_asset_rent.ASSET_CODE
     *
     * @mbggenerated
     */
    public String getAssetCode() {
        return assetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.ASSET_CODE
     *
     * @param assetCode the value for gm_asset_rent.ASSET_CODE
     *
     * @mbggenerated
     */
    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode == null ? null : assetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.LOAN_EMPLOYEECODE
     *
     * @return the value of gm_asset_rent.LOAN_EMPLOYEECODE
     *
     * @mbggenerated
     */
    public String getLoanEmployeecode() {
        return loanEmployeecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.LOAN_EMPLOYEECODE
     *
     * @param loanEmployeecode the value for gm_asset_rent.LOAN_EMPLOYEECODE
     *
     * @mbggenerated
     */
    public void setLoanEmployeecode(String loanEmployeecode) {
        this.loanEmployeecode = loanEmployeecode == null ? null : loanEmployeecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.LOAN_EMPLOYEENAME
     *
     * @return the value of gm_asset_rent.LOAN_EMPLOYEENAME
     *
     * @mbggenerated
     */
    public String getLoanEmployeename() {
        return loanEmployeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.LOAN_EMPLOYEENAME
     *
     * @param loanEmployeename the value for gm_asset_rent.LOAN_EMPLOYEENAME
     *
     * @mbggenerated
     */
    public void setLoanEmployeename(String loanEmployeename) {
        this.loanEmployeename = loanEmployeename == null ? null : loanEmployeename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.LOAN_UNIT_CODE
     *
     * @return the value of gm_asset_rent.LOAN_UNIT_CODE
     *
     * @mbggenerated
     */
    public String getLoanUnitCode() {
        return loanUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.LOAN_UNIT_CODE
     *
     * @param loanUnitCode the value for gm_asset_rent.LOAN_UNIT_CODE
     *
     * @mbggenerated
     */
    public void setLoanUnitCode(String loanUnitCode) {
        this.loanUnitCode = loanUnitCode == null ? null : loanUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.LOAN_UNIT_NAME
     *
     * @return the value of gm_asset_rent.LOAN_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getLoanUnitName() {
        return loanUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.LOAN_UNIT_NAME
     *
     * @param loanUnitName the value for gm_asset_rent.LOAN_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setLoanUnitName(String loanUnitName) {
        this.loanUnitName = loanUnitName == null ? null : loanUnitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.LOAN_PRO_NO
     *
     * @return the value of gm_asset_rent.LOAN_PRO_NO
     *
     * @mbggenerated
     */
    public String getLoanProNo() {
        return loanProNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.LOAN_PRO_NO
     *
     * @param loanProNo the value for gm_asset_rent.LOAN_PRO_NO
     *
     * @mbggenerated
     */
    public void setLoanProNo(String loanProNo) {
        this.loanProNo = loanProNo == null ? null : loanProNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.LOAN_PRO_NAME
     *
     * @return the value of gm_asset_rent.LOAN_PRO_NAME
     *
     * @mbggenerated
     */
    public String getLoanProName() {
        return loanProName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.LOAN_PRO_NAME
     *
     * @param loanProName the value for gm_asset_rent.LOAN_PRO_NAME
     *
     * @mbggenerated
     */
    public void setLoanProName(String loanProName) {
        this.loanProName = loanProName == null ? null : loanProName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.RENT_DATE
     *
     * @return the value of gm_asset_rent.RENT_DATE
     *
     * @mbggenerated
     */
    public String getRentDate() {
        return rentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.RENT_DATE
     *
     * @param rentDate the value for gm_asset_rent.RENT_DATE
     *
     * @mbggenerated
     */
    public void setRentDate(String rentDate) {
        this.rentDate = rentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.ESTIMATE_RETURN_DATE
     *
     * @return the value of gm_asset_rent.ESTIMATE_RETURN_DATE
     *
     * @mbggenerated
     */
    public String getEstimateReturnDate() {
        return estimateReturnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.ESTIMATE_RETURN_DATE
     *
     * @param estimateReturnDate the value for gm_asset_rent.ESTIMATE_RETURN_DATE
     *
     * @mbggenerated
     */
    public void setEstimateReturnDate(String estimateReturnDate) {
        this.estimateReturnDate = estimateReturnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.RETURN_DATE
     *
     * @return the value of gm_asset_rent.RETURN_DATE
     *
     * @mbggenerated
     */
    public String getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.RETURN_DATE
     *
     * @param returnDate the value for gm_asset_rent.RETURN_DATE
     *
     * @mbggenerated
     */
    public void setReturnDate(String returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.RENT_STATUS
     *
     * @return the value of gm_asset_rent.RENT_STATUS
     *
     * @mbggenerated
     */
    public Integer getRentStatus() {
        return rentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.RENT_STATUS
     *
     * @param rentStatus the value for gm_asset_rent.RENT_STATUS
     *
     * @mbggenerated
     */
    public void setRentStatus(Integer rentStatus) {
        this.rentStatus = rentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.FLOW_STATUS
     *
     * @return the value of gm_asset_rent.FLOW_STATUS
     *
     * @mbggenerated
     */
    public Integer getFlowStatus() {
        return flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.FLOW_STATUS
     *
     * @param flowStatus the value for gm_asset_rent.FLOW_STATUS
     *
     * @mbggenerated
     */
    public void setFlowStatus(Integer flowStatus) {
        this.flowStatus = flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.SYS_CREATE_TIME
     *
     * @return the value of gm_asset_rent.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public String getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for gm_asset_rent.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(String sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.SYS_UPDATE_TIME
     *
     * @return the value of gm_asset_rent.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for gm_asset_rent.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(String sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.SYS_DELETE_TIME
     *
     * @return the value of gm_asset_rent.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public String getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for gm_asset_rent.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(String sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.SYS_PROCESS_FLAG
     *
     * @return the value of gm_asset_rent.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for gm_asset_rent.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_rent.REMARKS
     *
     * @return the value of gm_asset_rent.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_rent.REMARKS
     *
     * @param remarks the value for gm_asset_rent.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	@Override
	protected Map doPreToMap() {
		Map params = new HashMap();
		return params;
	}

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub
		return null;
	}
}