package com.glens.pwCloudOs.pm.taskMgr.device.web;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import com.glens.eap.platform.core.web.ControllerForm;

public class PowerDeviceTypeForm extends ControllerForm  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_type.rowid
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_type.DEVICE_TYPE_CODE
     *
     * @mbggenerated
     */
    private String deviceTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_type.DEVICE_TYPE_NAME
     *
     * @mbggenerated
     */
    private String deviceTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_type.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_type.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_type.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private Date sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_type.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_device_type.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_type.rowid
     *
     * @return the value of power_device_type.rowid
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_type.rowid
     *
     * @param rowid the value for power_device_type.rowid
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_type.DEVICE_TYPE_CODE
     *
     * @return the value of power_device_type.DEVICE_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getDeviceTypeCode() {
        return deviceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_type.DEVICE_TYPE_CODE
     *
     * @param deviceTypeCode the value for power_device_type.DEVICE_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setDeviceTypeCode(String deviceTypeCode) {
        this.deviceTypeCode = deviceTypeCode == null ? null : deviceTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_type.DEVICE_TYPE_NAME
     *
     * @return the value of power_device_type.DEVICE_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getDeviceTypeName() {
        return deviceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_type.DEVICE_TYPE_NAME
     *
     * @param deviceTypeName the value for power_device_type.DEVICE_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setDeviceTypeName(String deviceTypeName) {
        this.deviceTypeName = deviceTypeName == null ? null : deviceTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_type.SYS_CREATE_TIME
     *
     * @return the value of power_device_type.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_type.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for power_device_type.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(Date sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_type.SYS_UPDATE_TIME
     *
     * @return the value of power_device_type.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_type.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for power_device_type.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(Date sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_type.SYS_DELETE_TIME
     *
     * @return the value of power_device_type.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_type.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for power_device_type.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(Date sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_type.SYS_PROCESS_FLAG
     *
     * @return the value of power_device_type.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_type.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for power_device_type.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_device_type.REMARKS
     *
     * @return the value of power_device_type.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_device_type.REMARKS
     *
     * @param remarks the value for power_device_type.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	@Override
	protected Map doPreToMap() {
		Map map=new HashMap();
		return map;
	}

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub
		return null;
	}
}