package com.glens.pwCloudOs.materielMg.vehicleMg.fuelCard.vo;

import com.glens.eap.platform.core.beans.ValueObject;

public class FuelCardVo implements ValueObject {

	private Long rowid;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.FUELCARD_NO
     *
     * @mbggenerated
     */
    private String fuelcardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.ASSET_CODE
     *
     * @mbggenerated
     */
    private String assetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.MATTER_TIME
     *
     * @mbggenerated
     */
    private String matterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.AMOUNT
     *
     * @mbggenerated
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;
    
    private String vaNo;

    public Long getRowid() {
		return rowid;
	}

	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard.FUELCARD_NO
     *
     * @return the value of gm_vm_fuelcard.FUELCARD_NO
     *
     * @mbggenerated
     */
    public String getFuelcardNo() {
        return fuelcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard.FUELCARD_NO
     *
     * @param fuelcardNo the value for gm_vm_fuelcard.FUELCARD_NO
     *
     * @mbggenerated
     */
    public void setFuelcardNo(String fuelcardNo) {
        this.fuelcardNo = fuelcardNo == null ? null : fuelcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard.ASSET_CODE
     *
     * @return the value of gm_vm_fuelcard.ASSET_CODE
     *
     * @mbggenerated
     */
    public String getAssetCode() {
        return assetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard.ASSET_CODE
     *
     * @param assetCode the value for gm_vm_fuelcard.ASSET_CODE
     *
     * @mbggenerated
     */
    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode == null ? null : assetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard.MATTER_TIME
     *
     * @return the value of gm_vm_fuelcard.MATTER_TIME
     *
     * @mbggenerated
     */
    public String getMatterTime() {
        return matterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard.MATTER_TIME
     *
     * @param matterTime the value for gm_vm_fuelcard.MATTER_TIME
     *
     * @mbggenerated
     */
    public void setMatterTime(String matterTime) {
        this.matterTime = matterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard.AMOUNT
     *
     * @return the value of gm_vm_fuelcard.AMOUNT
     *
     * @mbggenerated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard.AMOUNT
     *
     * @param amount the value for gm_vm_fuelcard.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard.STATUS
     *
     * @return the value of gm_vm_fuelcard.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard.STATUS
     *
     * @param status the value for gm_vm_fuelcard.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard.REMARKS
     *
     * @return the value of gm_vm_fuelcard.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard.REMARKS
     *
     * @param remarks the value for gm_vm_fuelcard.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	public String getVaNo() {
		return vaNo;
	}

	public void setVaNo(String vaNo) {
		this.vaNo = vaNo;
	}
}