/**
 * @Title: FuelCardForm.java
 * @Package com.glens.pwCloudOs.materielMg.vehicleMg.fuelCard.web
 * @Description: TODO
 * Copyright: Copyright (c) 2016 
 * Company:南京量为石信息科技有限公司
 * @author 
 * @date 2016-6-23 下午5:53:00
 * @version V1.0
 */


package com.glens.pwCloudOs.materielMg.vehicleMg.fuelCard.web;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import com.glens.eap.platform.core.annotation.ValueObjectProcessor;
import com.glens.eap.platform.core.web.ControllerForm;

/**
 * 
 * 
 * @author 
 * @version V1.0
 */

@ValueObjectProcessor(clazz="com.glens.pwCloudOs.materielMg.vehicleMg.fuelCard.vo.FuelCardVo")
public class FuelCardForm extends ControllerForm {

	private Long rowid;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.FUELCARD_NO
     *
     * @mbggenerated
     */
    private String fuelcardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.ASSET_CODE
     *
     * @mbggenerated
     */
    private String assetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.MATTER_TIME
     *
     * @mbggenerated
     */
    private String matterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.AMOUNT
     *
     * @mbggenerated
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;
    
    private String searchName;
	
	/**
	
	 * <p>Title: doPreToMap</p>
	
	 * <p>Description: </p>
	
	 * @return
	
	 * @see com.glens.eap.platform.core.web.ControllerForm#doPreToMap()
	
	 **/

	@Override
	protected Map doPreToMap() {
		// TODO Auto-generated method stub

		Map<String, String> params = new HashMap<String, String>();
		params.put("searchName", searchName);
		
		return params;
	}

	/**
	
	 * <p>Title: doPostRequest</p>
	
	 * <p>Description: </p>
	
	 * @param request
	
	 * @see com.glens.eap.platform.core.web.ControllerForm#doPostRequest(javax.servlet.http.HttpServletRequest)
	
	 **/

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub

	}

	/**
	
	 * <p>Title: getGenerateKey</p>
	
	 * <p>Description: </p>
	
	 * @return
	
	 * @see com.glens.eap.platform.core.web.ControllerForm#getGenerateKey()
	
	 **/

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub

		return null;
	}

	public Long getRowid() {
		return rowid;
	}

	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	public String getFuelcardNo() {
		return fuelcardNo;
	}

	public void setFuelcardNo(String fuelcardNo) {
		this.fuelcardNo = fuelcardNo;
	}

	public String getAssetCode() {
		return assetCode;
	}

	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode;
	}

	public String getMatterTime() {
		return matterTime;
	}

	public void setMatterTime(String matterTime) {
		this.matterTime = matterTime;
	}

	public Float getAmount() {
		return amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getSearchName() {
		return searchName;
	}

	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}

}
