package com.glens.pwCloudOs.pm.scene.web;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import com.glens.eap.platform.core.annotation.ValueObjectProcessor;
import com.glens.eap.platform.core.web.ControllerForm;

@ValueObjectProcessor(clazz = "com.glens.pwCloudOs.pm.scene.vo.PmSceneEnv")
public class PmSceneEnvForm extends ControllerForm {
	private Long rowid;

	private String companyCode;

	private String proNo;

	private String spotCode;

	private String reportEmployeecode;

	private String reportTime;

	private String fileType;

	private String fileCode;

	private String files;// TODO Base64数据上传？文件太大估计会有问题，待确定！

	private String sceneDescr;

	private String positionX;

	private String positionY;

	private String startTime;

	private String endTime;

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pm_scene_env.ROWID
	 * 
	 * @return the value of pm_scene_env.ROWID
	 * 
	 * @mbggenerated
	 */
	public Long getRowid() {
		return rowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pm_scene_env.ROWID
	 * 
	 * @param rowid
	 *            the value for pm_scene_env.ROWID
	 * 
	 * @mbggenerated
	 */
	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pm_scene_env.COMPANY_CODE
	 * 
	 * @return the value of pm_scene_env.COMPANY_CODE
	 * 
	 * @mbggenerated
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pm_scene_env.COMPANY_CODE
	 * 
	 * @param companyCode
	 *            the value for pm_scene_env.COMPANY_CODE
	 * 
	 * @mbggenerated
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode == null ? null : companyCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pm_scene_env.PRO_NO
	 * 
	 * @return the value of pm_scene_env.PRO_NO
	 * 
	 * @mbggenerated
	 */
	public String getProNo() {
		return proNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pm_scene_env.PRO_NO
	 * 
	 * @param proNo
	 *            the value for pm_scene_env.PRO_NO
	 * 
	 * @mbggenerated
	 */
	public void setProNo(String proNo) {
		this.proNo = proNo == null ? null : proNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pm_scene_env.EMPLOYEECODE
	 * 
	 * @return the value of pm_scene_env.EMPLOYEECODE
	 * 
	 * @mbggenerated
	 */
	public String getReportEmployeecode() {
		return reportEmployeecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pm_scene_env.EMPLOYEECODE
	 * 
	 * @param reportEmployeecode
	 *            the value for pm_scene_env.EMPLOYEECODE
	 * 
	 * @mbggenerated
	 */
	public void setReportEmployeecode(String reportEmployeecode) {
		this.reportEmployeecode = reportEmployeecode == null ? null
				: reportEmployeecode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pm_scene_env.REPORT_TIME
	 * 
	 * @return the value of pm_scene_env.REPORT_TIME
	 * 
	 * @mbggenerated
	 */
	public String getReportTime() {
		return reportTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pm_scene_env.REPORT_TIME
	 * 
	 * @param reportTime
	 *            the value for pm_scene_env.REPORT_TIME
	 * 
	 * @mbggenerated
	 */
	public void setReportTime(String reportTime) {
		this.reportTime = reportTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pm_scene_env.FILE_CODE
	 * 
	 * @return the value of pm_scene_env.FILE_CODE
	 * 
	 * @mbggenerated
	 */
	public String getFileCode() {
		return fileCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pm_scene_env.FILE_CODE
	 * 
	 * @param fileCode
	 *            the value for pm_scene_env.FILE_CODE
	 * 
	 * @mbggenerated
	 */
	public void setFileCode(String fileCode) {
		this.fileCode = fileCode == null ? null : fileCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pm_scene_env.SCENE_DESCR
	 * 
	 * @return the value of pm_scene_env.SCENE_DESCR
	 * 
	 * @mbggenerated
	 */
	public String getSceneDescr() {
		return sceneDescr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pm_scene_env.SCENE_DESCR
	 * 
	 * @param sceneDescr
	 *            the value for pm_scene_env.SCENE_DESCR
	 * 
	 * @mbggenerated
	 */
	public void setSceneDescr(String sceneDescr) {
		this.sceneDescr = sceneDescr == null ? null : sceneDescr.trim();
	}

	public String getFiles() {
		return files;
	}

	public void setFiles(String files) {
		this.files = files;
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public String getPositionX() {
		return positionX;
	}

	public void setPositionX(String positionX) {
		this.positionX = positionX;
	}

	public String getPositionY() {
		return positionY;
	}

	public void setPositionY(String positionY) {
		this.positionY = positionY;
	}

	public String getSpotCode() {
		return spotCode;
	}

	public void setSpotCode(String spotCode) {
		this.spotCode = spotCode;
	}

	@Override
	protected Map doPreToMap() {
		Map<String, Object> params = new HashMap<String, Object>();
		params.put("proNo", proNo);
		params.put("spotCode", spotCode);
		params.put("startTime", startTime);
		params.put("endTime", endTime);
		return params;
	}

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub

	}

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub
		return null;
	}

}
