package com.glens.pwCloudOs.pm.schedulePlan.worklist.vo;

import java.util.Date;
import java.util.List;

import com.glens.eap.platform.core.beans.ValueObject;

public class PmWorkHours implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;
    private String proName;
    private String proCode;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.WORK_DATE
     *
     * @mbggenerated
     */
    private String workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.WORKER
     *
     * @mbggenerated
     */
    private String worker;
    private String workerName;
    private String jobNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.WORK_HOURS
     *
     * @mbggenerated
     */
    private Float workHours;
    private Float attendanceHours;
    private Float moreHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.IS_PAID_LEAVE
     *
     * @mbggenerated
     */
    private Integer isPaidLeave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.PAID_HOURS
     *
     * @mbggenerated
     */
    private Float paidHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.PAID_LEAVE_TYPE
     *
     * @mbggenerated
     */
    private Integer paidLeaveType;
    private String paidLeaveTypeName;
    private Integer hasNotLocal;
    private Integer notLocalStandard;
    private String notLocalStandardName;
    private Integer hasMeal;
    private Integer mealStandard;
    private String mealStandardName;
    private Float pfmCoefficient;
    private Float regulativeHours;
    private String leaveDescr;
    private Integer checkStatus;
    private String checkTime;
    private String checkDescr;
    
    
    public String getCheckDescr() {
		return checkDescr;
	}

	public void setCheckDescr(String checkDescr) {
		this.checkDescr = checkDescr;
	}

	public String getCheckTime() {
		return checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	public Integer getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	public Float getMoreHours() {
		return moreHours;
	}

	public void setMoreHours(Float moreHours) {
		this.moreHours = moreHours;
	}

	public Float getAttendanceHours() {
		return attendanceHours;
	}

	public void setAttendanceHours(Float attendanceHours) {
		this.attendanceHours = attendanceHours;
	}

	public Float getPfmCoefficient() {
		return pfmCoefficient;
	}

	public void setPfmCoefficient(Float pfmCoefficient) {
		this.pfmCoefficient = pfmCoefficient;
	}

	public Float getRegulativeHours() {
		return regulativeHours;
	}

	public void setRegulativeHours(Float regulativeHours) {
		this.regulativeHours = regulativeHours;
	}

	public String getLeaveDescr() {
		return leaveDescr;
	}

	public void setLeaveDescr(String leaveDescr) {
		this.leaveDescr = leaveDescr;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private String sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private String sysUpdateTime;
    
    private List<PmWorkList> workList;
    

    public String getJobNo() {
		return jobNo;
	}

	public void setJobNo(String jobNo) {
		this.jobNo = jobNo;
	}

	public String getPaidLeaveTypeName() {
		if(paidLeaveType==null){
			return "无";
		}
    	switch(paidLeaveType){
	    	case 1:
	    		return "病假";
	    	case 2:
	    		return "产假";
	    	case 3:
	    		return "陪产假";
	    	case 4:
	    		return "婚假";
	    	case 5:
	    		return "丧假";
	    	case 6:
	    		return "年假";
	    	case 7:
	    		return "哺乳假";
	    	case 8:
	    		return "法定假日";
	    	case 9:
	    		return "其它";
	    	default:
	    		return "无";
    	}
	}

	public void setPaidLeaveTypeName(String paidLeaveTypeName) {
		this.paidLeaveTypeName = paidLeaveTypeName;
	}
	

	public String getNotLocalStandardName() {
		if(notLocalStandard==null){
			return "无";
		}
		switch(notLocalStandard){
	    	case 20:
	    		return "（省内）组员";
	    	case 30:
	    		return "（省内）合伙人、经理";
	    	case 40:
	    		return "（省外）组员";
	    	case 50:
	    		return "（省外）合伙人、经理";
	    	default:
	    		return "无";
		}
	}

	public void setNotLocalStandardName(String notLocalStandardName) {
		this.notLocalStandardName = notLocalStandardName;
	}

	public String getMealStandardName() {
		if(hasMeal==1){
	    	return "有";
		}else{
			return "无";
		}
	}

	public void setMealStandardName(String mealStandardName) {
		this.mealStandardName = mealStandardName;
	}

	public Integer getMealStandard() {
		if(hasMeal==1){
			return 15;
		}
		return mealStandard;
	}

	public void setMealStandard(Integer mealStandard) {
		this.mealStandard = mealStandard;
	}

	public Integer getNotLocalStandard() {
		return notLocalStandard;
	}

	public void setNotLocalStandard(Integer notLocalStandard) {
		this.notLocalStandard = notLocalStandard;
	}

	public String getProCode() {
		return proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

	public List<PmWorkList> getWorkList() {
		return workList;
	}

	public void setWorkList(List<PmWorkList> workList) {
		this.workList = workList;
	}

	public Integer getHasNotLocal() {
		return hasNotLocal;
	}

	public void setHasNotLocal(Integer hasNotLocal) {
		this.hasNotLocal = hasNotLocal;
	}

	public Integer getHasMeal() {
		return hasMeal;
	}

	public void setHasMeal(Integer hasMeal) {
		this.hasMeal = hasMeal;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getWorkerName() {
		return workerName;
	}

	public void setWorkerName(String workerName) {
		this.workerName = workerName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.ROWID
     *
     * @return the value of pm_work_hours.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.ROWID
     *
     * @param rowid the value for pm_work_hours.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.PRO_NO
     *
     * @return the value of pm_work_hours.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.PRO_NO
     *
     * @param proNo the value for pm_work_hours.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.WORK_DATE
     *
     * @return the value of pm_work_hours.WORK_DATE
     *
     * @mbggenerated
     */
    public String getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.WORK_DATE
     *
     * @param workDate the value for pm_work_hours.WORK_DATE
     *
     * @mbggenerated
     */
    public void setWorkDate(String workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.WORKER
     *
     * @return the value of pm_work_hours.WORKER
     *
     * @mbggenerated
     */
    public String getWorker() {
        return worker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.WORKER
     *
     * @param worker the value for pm_work_hours.WORKER
     *
     * @mbggenerated
     */
    public void setWorker(String worker) {
        this.worker = worker == null ? null : worker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.WORK_HOURS
     *
     * @return the value of pm_work_hours.WORK_HOURS
     *
     * @mbggenerated
     */
    public Float getWorkHours() {
        return workHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.WORK_HOURS
     *
     * @param workHours the value for pm_work_hours.WORK_HOURS
     *
     * @mbggenerated
     */
    public void setWorkHours(Float workHours) {
        this.workHours = workHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.IS_PAID_LEAVE
     *
     * @return the value of pm_work_hours.IS_PAID_LEAVE
     *
     * @mbggenerated
     */
    public Integer getIsPaidLeave() {
        return isPaidLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.IS_PAID_LEAVE
     *
     * @param isPaidLeave the value for pm_work_hours.IS_PAID_LEAVE
     *
     * @mbggenerated
     */
    public void setIsPaidLeave(Integer isPaidLeave) {
        this.isPaidLeave = isPaidLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.PAID_HOURS
     *
     * @return the value of pm_work_hours.PAID_HOURS
     *
     * @mbggenerated
     */
    public Float getPaidHours() {
        return paidHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.PAID_HOURS
     *
     * @param paidHours the value for pm_work_hours.PAID_HOURS
     *
     * @mbggenerated
     */
    public void setPaidHours(Float paidHours) {
        this.paidHours = paidHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.PAID_LEAVE_TYPE
     *
     * @return the value of pm_work_hours.PAID_LEAVE_TYPE
     *
     * @mbggenerated
     */
    public Integer getPaidLeaveType() {
        return paidLeaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.PAID_LEAVE_TYPE
     *
     * @param paidLeaveType the value for pm_work_hours.PAID_LEAVE_TYPE
     *
     * @mbggenerated
     */
    public void setPaidLeaveType(Integer paidLeaveType) {
        this.paidLeaveType = paidLeaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.SYS_CREATE_TIME
     *
     * @return the value of pm_work_hours.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public String getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for pm_work_hours.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(String sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.SYS_UPDATE_TIME
     *
     * @return the value of pm_work_hours.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for pm_work_hours.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(String sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }
}