package com.glens.pwCloudOs.pm.schedulePlan.worklist.vo;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class PmWorkListExcelVo implements ValueObject {
	private Integer listNum;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.IS_PAID_LEAVE
     *
     * @mbggenerated
     */
    private Integer isPaidLeave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.PAID_HOURS
     *
     * @mbggenerated
     */
    private Float paidHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.PAID_LEAVE_TYPE
     *
     * @mbggenerated
     */
    private Integer paidLeaveType;
    private Integer hasNotLocal;
    private Integer notLocalStandard;
    private Integer hasMeal;
    private Integer mealStandard;
    private Float pfmCoefficient;
    private Float regulativeHours;
    private String leaveDescr;
    
    
    public String getPaidLeaveTypeName() {
		if(paidLeaveType==null){
			return "无";
		}
    	switch(paidLeaveType){
	    	case 1:
	    		return "病假";
	    	case 2:
	    		return "产假";
	    	case 3:
	    		return "陪产假";
	    	case 4:
	    		return "婚假";
	    	case 5:
	    		return "丧假";
	    	case 6:
	    		return "年假";
	    	case 7:
	    		return "哺乳假";
	    	case 8:
	    		return "法定假日";
	    	case 9:
	    		return "其它";
	    	default:
	    		return "无";
    	}
	}
    public String getNotLocalStandardName() {
		if(notLocalStandard==null){
			return "无";
		}
		switch(notLocalStandard){
	    	case 20:
	    		return "（省内）组员";
	    	case 30:
	    		return "（省内）合伙人、经理";
	    	case 40:
	    		return "（省外）组员";
	    	case 50:
	    		return "（省外）合伙人、经理";
	    	default:
	    		return "无";
		}
	}
    public String getMealStandardName() {
		if(hasMeal!=null && hasMeal==1){
	    	return "有";
		}else{
			return "无";
		}
	}
    public Integer getMealStandard() {
		return mealStandard;
	}
    public String getCheckStatusName() {
    	if(checkStatus==1){
    		return "已审";
    	}else if(checkStatus==2){
    		return "退回";
    	}else{
    		return "未审";
    	}
	}

	public void setCheckStatusName(String checkStatusName) {
		if("已审".equals(checkStatusName)){
    		checkStatus=1;
    	}else if("退回".equals(checkStatusName)){
    		checkStatus=2;
    	}else{
    		checkStatus=0;
    	}
	}

	public Float getPfmCoefficient() {
		return pfmCoefficient;
	}

	public void setPfmCoefficient(Float pfmCoefficient) {
		this.pfmCoefficient = pfmCoefficient;
	}

	public Float getRegulativeHours() {
		return regulativeHours;
	}

	public void setRegulativeHours(Float regulativeHours) {
		this.regulativeHours = regulativeHours;
	}

	public String getLeaveDescr() {
		return leaveDescr;
	}

	public void setLeaveDescr(String leaveDescr) {
		this.leaveDescr = leaveDescr;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;
    private String proName;
    private String proCode;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORK_DATE
     *
     * @mbggenerated
     */
    private String workDate;
    private Float workHours;
    private Float attendanceHours;
    private Float moreHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORKER
     *
     * @mbggenerated
     */
    private String worker;
    private String workerName;
    private String jobNo;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORK_TYPE
     *
     * @mbggenerated
     */
    private String workType;
    private String workTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORKLOAD
     *
     * @mbggenerated
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORK_DESCR
     *
     * @mbggenerated
     */
    private String workDescr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.MARKER
     *
     * @mbggenerated
     */
    private String marker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.QUALITY_CHECK_USER
     *
     * @mbggenerated
     */
    private String qualityCheckUser;
    private String qualityCheckUserName;
    private String qualityCheckUserJobNo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.QUALITY_CHECK_DATE
     *
     * @mbggenerated
     */
    private String qualityCheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.IS_FAULT
     *
     * @mbggenerated
     */
    private Integer isFault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.FAULT_DESCR
     *
     * @mbggenerated
     */
    private String faultDescr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private String sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private String sysUpdateTime;

    private String categoryCode;
    private String categoryName;
    private String workTypeUnit;
    private Integer checkStatus;
    private String checkTime;
    
    
    public String getCheckTime() {
		return checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	public Integer getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	public Float getAttendanceHours() {
		return attendanceHours;
	}

	public void setAttendanceHours(Float attendanceHours) {
		this.attendanceHours = attendanceHours;
	}

	public void setNotLocalStandardName(String notLocalStandardName) {
		if("（省内）组员".equals(notLocalStandardName)){
			this.hasNotLocal=1;
			this.notLocalStandard=20;
		}else if("（省内）合伙人、经理".equals(notLocalStandardName)){
			this.hasNotLocal=1;
			this.notLocalStandard=30;
		}else if("（省外）组员".equals(notLocalStandardName)){
			this.hasNotLocal=1;
			this.notLocalStandard=40;
		}else if("（省外）合伙人、经理".equals(notLocalStandardName)){
			this.hasNotLocal=1;
			this.notLocalStandard=50;
		}
	}

	public void setMealStandardName(String mealStandardName) {
		if("有".equals(mealStandardName)){
			this.hasMeal = 1;
	    	this.mealStandard = 15;
		}else{
			this.hasMeal=0;
			this.mealStandard = 0;
		}
	}

	public Float getWorkHours() {
		return workHours;
	}

	public void setWorkHours(Float workHours) {
		this.workHours = workHours;
	}

	public void setMealStandard(Integer mealStandard) {
		this.mealStandard = mealStandard;
	}

	public void setPaidLeaveTypeName(String paidLeaveTypeName) {
		if("病假".equals(paidLeaveTypeName)){
			this.paidLeaveType=1;
		}else if("产假".equals(paidLeaveTypeName)){
			this.paidLeaveType=2;
		}else if("陪产假".equals(paidLeaveTypeName)){
			this.paidLeaveType=3;
		}else if("婚假".equals(paidLeaveTypeName)){
			this.paidLeaveType=4;
		}else if("丧假".equals(paidLeaveTypeName)){
			this.paidLeaveType=5;
		}else if("年假".equals(paidLeaveTypeName)){
			this.paidLeaveType=6;
		}else if("哺乳假".equals(paidLeaveTypeName)){
			this.paidLeaveType=7;
		}else if("法定假日".equals(paidLeaveTypeName)){
			this.paidLeaveType=8;
		}else if("其它".equals(paidLeaveTypeName)){
			this.paidLeaveType=9;
		}
	}

	public Integer getNotLocalStandard() {
		return notLocalStandard;
	}

	public void setNotLocalStandard(Integer notLocalStandard) {
		this.notLocalStandard = notLocalStandard;
	}

	public String getJobNo() {
		return jobNo;
	}

	public void setJobNo(String jobNo) {
		this.jobNo = jobNo;
	}

	public String getQualityCheckUserJobNo() {
		return qualityCheckUserJobNo;
	}

	public void setQualityCheckUserJobNo(String qualityCheckUserJobNo) {
		this.qualityCheckUserJobNo = qualityCheckUserJobNo;
	}

	public String getProCode() {
		return proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

	public String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getWorkTypeUnit() {
		return workTypeUnit;
	}

	public void setWorkTypeUnit(String workTypeUnit) {
		this.workTypeUnit = workTypeUnit;
	}

	public Integer getIsPaidLeave() {
		return isPaidLeave;
	}

	public void setIsPaidLeave(Integer isPaidLeave) {
		this.isPaidLeave = isPaidLeave;
	}

	public Float getPaidHours() {
		return paidHours;
	}

	public void setPaidHours(Float paidHours) {
		this.paidHours = paidHours;
	}

	public Integer getPaidLeaveType() {
		return paidLeaveType;
	}

	public void setPaidLeaveType(Integer paidLeaveType) {
		this.paidLeaveType = paidLeaveType;
	}

	public Integer getHasNotLocal() {
		return hasNotLocal;
	}

	public void setHasNotLocal(Integer hasNotLocal) {
		this.hasNotLocal = hasNotLocal;
	}

	public Integer getHasMeal() {
		return hasMeal;
	}

	public void setHasMeal(Integer hasMeal) {
		this.hasMeal = hasMeal;
	}

	public String getWorkTypeName() {
		return workTypeName;
	}

	public void setWorkTypeName(String workTypeName) {
		this.workTypeName = workTypeName;
	}

	public Integer getListNum() {
		return listNum;
	}

	public void setListNum(Integer listNum) {
		this.listNum = listNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.ROWID
     *
     * @return the value of pm_work_list.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.ROWID
     *
     * @param rowid the value for pm_work_list.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.PRO_NO
     *
     * @return the value of pm_work_list.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.PRO_NO
     *
     * @param proNo the value for pm_work_list.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.WORK_DATE
     *
     * @return the value of pm_work_list.WORK_DATE
     *
     * @mbggenerated
     */
    public String getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.WORK_DATE
     *
     * @param workDate the value for pm_work_list.WORK_DATE
     *
     * @mbggenerated
     */
    public void setWorkDate(String workDate) {
        this.workDate = workDate;
    }
    
//    public void setWorkDate(String workDate) {
////    	Date date = null;
////    	if(workDate!=null && workDate.length()>0){
////    		try {
////				date = new SimpleDateFormat("yyyy-MM-dd").parse(workDate);
////			} catch (ParseException e) {
////			}
////    	}
//        this.workDate = workDate;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.WORKER
     *
     * @return the value of pm_work_list.WORKER
     *
     * @mbggenerated
     */
    public String getWorker() {
        return worker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.WORKER
     *
     * @param worker the value for pm_work_list.WORKER
     *
     * @mbggenerated
     */
    public void setWorker(String worker) {
        this.worker = worker == null ? null : worker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.WORK_TYPE
     *
     * @return the value of pm_work_list.WORK_TYPE
     *
     * @mbggenerated
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.WORK_TYPE
     *
     * @param workType the value for pm_work_list.WORK_TYPE
     *
     * @mbggenerated
     */
    public void setWorkType(String workType) {
        this.workType = workType == null ? null : workType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.WORKLOAD
     *
     * @return the value of pm_work_list.WORKLOAD
     *
     * @mbggenerated
     */
    public Float getWorkload() {
        return workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.WORKLOAD
     *
     * @param workload the value for pm_work_list.WORKLOAD
     *
     * @mbggenerated
     */
    public void setWorkload(Float workload) {
        this.workload = workload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.WORK_DESCR
     *
     * @return the value of pm_work_list.WORK_DESCR
     *
     * @mbggenerated
     */
    public String getWorkDescr() {
        return workDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.WORK_DESCR
     *
     * @param workDescr the value for pm_work_list.WORK_DESCR
     *
     * @mbggenerated
     */
    public void setWorkDescr(String workDescr) {
        this.workDescr = workDescr == null ? null : workDescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.MARKER
     *
     * @return the value of pm_work_list.MARKER
     *
     * @mbggenerated
     */
    public String getMarker() {
        return marker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.MARKER
     *
     * @param marker the value for pm_work_list.MARKER
     *
     * @mbggenerated
     */
    public void setMarker(String marker) {
        this.marker = marker == null ? null : marker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.QUALITY_CHECK_USER
     *
     * @return the value of pm_work_list.QUALITY_CHECK_USER
     *
     * @mbggenerated
     */
    public String getQualityCheckUser() {
        return qualityCheckUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.QUALITY_CHECK_USER
     *
     * @param qualityCheckUser the value for pm_work_list.QUALITY_CHECK_USER
     *
     * @mbggenerated
     */
    public void setQualityCheckUser(String qualityCheckUser) {
        this.qualityCheckUser = qualityCheckUser == null ? null : qualityCheckUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.QUALITY_CHECK_DATE
     *
     * @return the value of pm_work_list.QUALITY_CHECK_DATE
     *
     * @mbggenerated
     */
    public String getQualityCheckDate() {
        return qualityCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.QUALITY_CHECK_DATE
     *
     * @param qualityCheckDate the value for pm_work_list.QUALITY_CHECK_DATE
     *
     * @mbggenerated
     */
    public void setQualityCheckDate(String qualityCheckDate) {
        this.qualityCheckDate = qualityCheckDate;
    }
    
//    public void setQualityCheckDate(String qualityCheckDate) {
//    	Date date = null;
//    	if(qualityCheckDate!=null && qualityCheckDate.length()>0){
//    		try {
//    			date = new SimpleDateFormat("yyyy-MM-dd").parse(qualityCheckDate);
//    		} catch (ParseException e) {
//    		}
//    	}
//    	this.qualityCheckDate = date;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.IS_FAULT
     *
     * @return the value of pm_work_list.IS_FAULT
     *
     * @mbggenerated
     */
    public Integer getIsFault() {
        return isFault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.IS_FAULT
     *
     * @param isFault the value for pm_work_list.IS_FAULT
     *
     * @mbggenerated
     */
    public void setIsFault(Integer isFault) {
        this.isFault = isFault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.FAULT_DESCR
     *
     * @return the value of pm_work_list.FAULT_DESCR
     *
     * @mbggenerated
     */
    public String getFaultDescr() {
        return faultDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.FAULT_DESCR
     *
     * @param faultDescr the value for pm_work_list.FAULT_DESCR
     *
     * @mbggenerated
     */
    public void setFaultDescr(String faultDescr) {
        this.faultDescr = faultDescr == null ? null : faultDescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.SYS_CREATE_TIME
     *
     * @return the value of pm_work_list.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public String getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for pm_work_list.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(String sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_list.SYS_UPDATE_TIME
     *
     * @return the value of pm_work_list.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_list.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for pm_work_list.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(String sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getWorkerName() {
		return workerName;
	}

	public void setWorkerName(String workerName) {
		this.workerName = workerName;
	}

	public String getQualityCheckUserName() {
		return qualityCheckUserName;
	}

	public void setQualityCheckUserName(String qualityCheckUserName) {
		this.qualityCheckUserName = qualityCheckUserName;
	}

	public Float getMoreHours() {
		return moreHours;
	}

	public void setMoreHours(Float moreHours) {
		this.moreHours = moreHours;
	}
    
}