package com.glens.pwCloudOs.pm.schedulePlan.scheduleDaily.web;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import com.glens.eap.platform.core.annotation.ValueObjectProcessor;
import com.glens.eap.platform.core.web.ControllerForm;

@ValueObjectProcessor(clazz = "com.glens.pwCloudOs.pm.schedulePlan.scheduleDaily.vo.PmDayKpi")
public class PmDayKpiForm extends ControllerForm{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.rowid
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.PRO_NAME
     *
     * @mbggenerated
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.KPI_CODE
     *
     * @mbggenerated
     */
    private String kpiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.KPI_VALUE
     *
     * @mbggenerated
     */
    private Float kpiValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.ATTACHED_VALUE
     *
     * @mbggenerated
     */
    private Float attachedValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.REPORT_DATE
     *
     * @mbggenerated
     */
    private String reportDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private String sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private String sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private String sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_kpi.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.rowid
     *
     * @return the value of pm_day_kpi.rowid
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.rowid
     *
     * @param rowid the value for pm_day_kpi.rowid
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.COMPANY_CODE
     *
     * @return the value of pm_day_kpi.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.COMPANY_CODE
     *
     * @param companyCode the value for pm_day_kpi.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.PRO_NO
     *
     * @return the value of pm_day_kpi.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.PRO_NO
     *
     * @param proNo the value for pm_day_kpi.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.PRO_NAME
     *
     * @return the value of pm_day_kpi.PRO_NAME
     *
     * @mbggenerated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.PRO_NAME
     *
     * @param proName the value for pm_day_kpi.PRO_NAME
     *
     * @mbggenerated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.KPI_CODE
     *
     * @return the value of pm_day_kpi.KPI_CODE
     *
     * @mbggenerated
     */
    public String getKpiCode() {
        return kpiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.KPI_CODE
     *
     * @param kpiCode the value for pm_day_kpi.KPI_CODE
     *
     * @mbggenerated
     */
    public void setKpiCode(String kpiCode) {
        this.kpiCode = kpiCode == null ? null : kpiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.KPI_VALUE
     *
     * @return the value of pm_day_kpi.KPI_VALUE
     *
     * @mbggenerated
     */
    public Float getKpiValue() {
        return kpiValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.KPI_VALUE
     *
     * @param kpiValue the value for pm_day_kpi.KPI_VALUE
     *
     * @mbggenerated
     */
    public void setKpiValue(Float kpiValue) {
        this.kpiValue = kpiValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.ATTACHED_VALUE
     *
     * @return the value of pm_day_kpi.ATTACHED_VALUE
     *
     * @mbggenerated
     */
    public Float getAttachedValue() {
        return attachedValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.ATTACHED_VALUE
     *
     * @param attachedValue the value for pm_day_kpi.ATTACHED_VALUE
     *
     * @mbggenerated
     */
    public void setAttachedValue(Float attachedValue) {
        this.attachedValue = attachedValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.REPORT_DATE
     *
     * @return the value of pm_day_kpi.REPORT_DATE
     *
     * @mbggenerated
     */
    public String getReportDate() {
        return reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.REPORT_DATE
     *
     * @param reportDate the value for pm_day_kpi.REPORT_DATE
     *
     * @mbggenerated
     */
    public void setReportDate(String reportDate) {
        this.reportDate = reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.SYS_CREATE_TIME
     *
     * @return the value of pm_day_kpi.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public String getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for pm_day_kpi.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(String sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.SYS_UPDATE_TIME
     *
     * @return the value of pm_day_kpi.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for pm_day_kpi.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(String sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.SYS_DELETE_TIME
     *
     * @return the value of pm_day_kpi.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public String getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for pm_day_kpi.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(String sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.SYS_PROCESS_FLAG
     *
     * @return the value of pm_day_kpi.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for pm_day_kpi.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_kpi.REMARKS
     *
     * @return the value of pm_day_kpi.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_kpi.REMARKS
     *
     * @param remarks the value for pm_day_kpi.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	@Override
	protected Map doPreToMap() {
		Map map = new HashMap();
		return map;
	}

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub
		return null;
	}
}