package com.glens.pwCloudOs.materielMg.vehicleMg.recharge.vo;

import com.glens.eap.platform.core.beans.ValueObject;

public class RechargeVo implements ValueObject {

	private Long rowid;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard_recharge.FUELCARD_NO
     *
     * @mbggenerated
     */
    private String fuelcardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard_recharge.RECHARGE_DATE
     *
     * @mbggenerated
     */
    private String rechargeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard_recharge.RECHARGE_AMOUNT
     *
     * @mbggenerated
     */
    private Integer rechargeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard_recharge.RECHARGE_SHOP
     *
     * @mbggenerated
     */
    private String rechargeShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_fuelcard_recharge.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    public Long getRowid() {
		return rowid;
	}

	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard_recharge.FUELCARD_NO
     *
     * @return the value of gm_vm_fuelcard_recharge.FUELCARD_NO
     *
     * @mbggenerated
     */
    public String getFuelcardNo() {
        return fuelcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard_recharge.FUELCARD_NO
     *
     * @param fuelcardNo the value for gm_vm_fuelcard_recharge.FUELCARD_NO
     *
     * @mbggenerated
     */
    public void setFuelcardNo(String fuelcardNo) {
        this.fuelcardNo = fuelcardNo == null ? null : fuelcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard_recharge.RECHARGE_DATE
     *
     * @return the value of gm_vm_fuelcard_recharge.RECHARGE_DATE
     *
     * @mbggenerated
     */
    public String getRechargeDate() {
        return rechargeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard_recharge.RECHARGE_DATE
     *
     * @param rechargeDate the value for gm_vm_fuelcard_recharge.RECHARGE_DATE
     *
     * @mbggenerated
     */
    public void setRechargeDate(String rechargeDate) {
        this.rechargeDate = rechargeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard_recharge.RECHARGE_AMOUNT
     *
     * @return the value of gm_vm_fuelcard_recharge.RECHARGE_AMOUNT
     *
     * @mbggenerated
     */
    public Integer getRechargeAmount() {
        return rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard_recharge.RECHARGE_AMOUNT
     *
     * @param rechargeAmount the value for gm_vm_fuelcard_recharge.RECHARGE_AMOUNT
     *
     * @mbggenerated
     */
    public void setRechargeAmount(Integer rechargeAmount) {
        this.rechargeAmount = rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard_recharge.RECHARGE_SHOP
     *
     * @return the value of gm_vm_fuelcard_recharge.RECHARGE_SHOP
     *
     * @mbggenerated
     */
    public String getRechargeShop() {
        return rechargeShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard_recharge.RECHARGE_SHOP
     *
     * @param rechargeShop the value for gm_vm_fuelcard_recharge.RECHARGE_SHOP
     *
     * @mbggenerated
     */
    public void setRechargeShop(String rechargeShop) {
        this.rechargeShop = rechargeShop == null ? null : rechargeShop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_fuelcard_recharge.REMARKS
     *
     * @return the value of gm_vm_fuelcard_recharge.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_fuelcard_recharge.REMARKS
     *
     * @param remarks the value for gm_vm_fuelcard_recharge.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}