package com.glens.pwCloudOs.materielMg.dormMg.dorm.vo;

import java.math.BigDecimal;

import org.springframework.web.multipart.MultipartFile;

import com.glens.eap.platform.core.beans.ValueObject;

public class DormVo implements ValueObject {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.DORM_CODE
     *
     * @mbggenerated
     */
    private String dormCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.DORM_NAME
     *
     * @mbggenerated
     */
    private String dormName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.REGION_CODE
     *
     * @mbggenerated
     */
    private String province;
    
    private String city;
    
    private String refundaMount;
    
    public String getRefundaMount() {
		return refundaMount;
	}

	public void setRefundaMount(String refundaMount) {
		this.refundaMount = refundaMount;
	}

	private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.X
     *
     * @mbggenerated
     */
    private String x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.Y
     *
     * @mbggenerated
     */
    private String y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.AREA
     *
     * @mbggenerated
     */
    private Float area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.HOUSETYPE
     *
     * @mbggenerated
     */
    private String housetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.S_RENT_DATE
     *
     * @mbggenerated
     */
    private String srentDate;
    
    private String frentDate;

    public String getFrentDate() {
		return frentDate;
	}

	public void setFrentDate(String frentDate) {
		this.frentDate = frentDate;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.E_RENT_DATE
     *
     * @mbggenerated
     */
    private String erentDate;

    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.MONTHRENT
     *
     * @mbggenerated
     */
    private Integer monthrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.DEPOSIT
     *
     * @mbggenerated
     */
    private Integer deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.MAX_BEDS
     *
     * @mbggenerated
     */
    private Integer maxBeds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.CUR_BEDS
     *
     * @mbggenerated
     */
    private Integer curBeds;
    
    private Integer hasbed;
    
    private String agency;//中介
    private String landlord;//房东
    private String operator;//经办人
    private String contractLease;//本次合同租期
    private String paymentMode;//支付方式
    private int  agencyAmount;//中介费
    
    private String refundDate;//退租时间
    private String refundDesc;//退组说明
    
    private MultipartFile contractDoc;
    private MultipartFile invoicejDoc;
    private String picTitle;
    private String contractDate;
    private String invoiceDate;
    
    

    public String getContractDate() {
		return contractDate;
	}

	public void setContractDate(String contractDate) {
		this.contractDate = contractDate;
	}

	public String getInvoiceDate() {
		return invoiceDate;
	}

	public void setInvoiceDate(String invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public String getPicTitle() {
		return picTitle;
	}

	public void setPicTitle(String picTitle) {
		this.picTitle = picTitle;
	}

	public MultipartFile getContractDoc() {
		return contractDoc;
	}

	public void setContractDoc(MultipartFile contractDoc) {
		this.contractDoc = contractDoc;
	}

	public MultipartFile getInvoicejDoc() {
		return invoicejDoc;
	}

	public void setInvoicejDoc(MultipartFile invoicejDoc) {
		this.invoicejDoc = invoicejDoc;
	}

	public String getPaymentMode() {
		return paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	public int getAgencyAmount() {
		return agencyAmount;
	}

	public void setAgencyAmount(int agencyAmount) {
		this.agencyAmount = agencyAmount;
	}

	public String getRefundDate() {
		return refundDate;
	}

	public void setRefundDate(String refundDate) {
		this.refundDate = refundDate;
	}

	public String getRefundDesc() {
		return refundDesc;
	}

	public void setRefundDesc(String refundDesc) {
		this.refundDesc = refundDesc;
	}

	public String getAgency() {
		return agency;
	}

	public void setAgency(String agency) {
		this.agency = agency;
	}

	public String getLandlord() {
		return landlord;
	}

	public void setLandlord(String landlord) {
		this.landlord = landlord;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getContractLease() {
		return contractLease;
	}

	public void setContractLease(String contractLease) {
		this.contractLease = contractLease;
	}

	public Integer getHasbed() {
		return hasbed;
	}

	public void setHasbed(Integer hasbed) {
		this.hasbed = hasbed;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.CUR_PRO_NOS
     *
     * @mbggenerated
     */
    private String curProNos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.CUR_PRO_NAMES
     *
     * @mbggenerated
     */
    private String curProNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.CUR_PRO_BEDS
     *
     * @mbggenerated
     */
    private String curProBeds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.DAYRENT
     *
     * @mbggenerated
     */
    private float dayrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.DORM_STATUS
     *
     * @mbggenerated
     */
    private Integer dormStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_bm_dorm.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.DORM_CODE
     *
     * @return the value of gm_bm_dorm.DORM_CODE
     *
     * @mbggenerated
     */
    public String getDormCode() {
        return dormCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.DORM_CODE
     *
     * @param dormCode the value for gm_bm_dorm.DORM_CODE
     *
     * @mbggenerated
     */
    public void setDormCode(String dormCode) {
        this.dormCode = dormCode == null ? null : dormCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.DORM_NAME
     *
     * @return the value of gm_bm_dorm.DORM_NAME
     *
     * @mbggenerated
     */
    public String getDormName() {
        return dormName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.DORM_NAME
     *
     * @param dormName the value for gm_bm_dorm.DORM_NAME
     *
     * @mbggenerated
     */
    public void setDormName(String dormName) {
        this.dormName = dormName == null ? null : dormName.trim();
    }

    public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.X
     *
     * @return the value of gm_bm_dorm.X
     *
     * @mbggenerated
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.X
     *
     * @param x the value for gm_bm_dorm.X
     *
     * @mbggenerated
     */
    public void setX(String x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.Y
     *
     * @return the value of gm_bm_dorm.Y
     *
     * @mbggenerated
     */
    public String getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.Y
     *
     * @param y the value for gm_bm_dorm.Y
     *
     * @mbggenerated
     */
    public void setY(String y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.AREA
     *
     * @return the value of gm_bm_dorm.AREA
     *
     * @mbggenerated
     */
    public Float getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.AREA
     *
     * @param area the value for gm_bm_dorm.AREA
     *
     * @mbggenerated
     */
    public void setArea(Float area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.HOUSETYPE
     *
     * @return the value of gm_bm_dorm.HOUSETYPE
     *
     * @mbggenerated
     */
    public String getHousetype() {
        return housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.HOUSETYPE
     *
     * @param housetype the value for gm_bm_dorm.HOUSETYPE
     *
     * @mbggenerated
     */
    public void setHousetype(String housetype) {
        this.housetype = housetype == null ? null : housetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.S_RENT_DATE
     *
     * @return the value of gm_bm_dorm.S_RENT_DATE
     *
     * @mbggenerated
     */
    public String getSrentDate() {
        return srentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.S_RENT_DATE
     *
     * @param sRentDate the value for gm_bm_dorm.S_RENT_DATE
     *
     * @mbggenerated
     */
    public void setSrentDate(String srentDate) {
        this.srentDate = srentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.E_RENT_DATE
     *
     * @return the value of gm_bm_dorm.E_RENT_DATE
     *
     * @mbggenerated
     */
    public String getErentDate() {
        return erentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.E_RENT_DATE
     *
     * @param eRentDate the value for gm_bm_dorm.E_RENT_DATE
     *
     * @mbggenerated
     */
    public void setErentDate(String erentDate) {
        this.erentDate = erentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.MONTHRENT
     *
     * @return the value of gm_bm_dorm.MONTHRENT
     *
     * @mbggenerated
     */
    public Integer getMonthrent() {
        return monthrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.MONTHRENT
     *
     * @param monthrent the value for gm_bm_dorm.MONTHRENT
     *
     * @mbggenerated
     */
    public void setMonthrent(Integer monthrent) {
        this.monthrent = monthrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.DEPOSIT
     *
     * @return the value of gm_bm_dorm.DEPOSIT
     *
     * @mbggenerated
     */
    public Integer getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.DEPOSIT
     *
     * @param deposit the value for gm_bm_dorm.DEPOSIT
     *
     * @mbggenerated
     */
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.MAX_BEDS
     *
     * @return the value of gm_bm_dorm.MAX_BEDS
     *
     * @mbggenerated
     */
    public Integer getMaxBeds() {
        return maxBeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.MAX_BEDS
     *
     * @param maxBeds the value for gm_bm_dorm.MAX_BEDS
     *
     * @mbggenerated
     */
    public void setMaxBeds(Integer maxBeds) {
        this.maxBeds = maxBeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.CUR_BEDS
     *
     * @return the value of gm_bm_dorm.CUR_BEDS
     *
     * @mbggenerated
     */
    public Integer getCurBeds() {
        return curBeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.CUR_BEDS
     *
     * @param curBeds the value for gm_bm_dorm.CUR_BEDS
     *
     * @mbggenerated
     */
    public void setCurBeds(Integer curBeds) {
        this.curBeds = curBeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.CUR_PRO_NOS
     *
     * @return the value of gm_bm_dorm.CUR_PRO_NOS
     *
     * @mbggenerated
     */
    public String getCurProNos() {
        return curProNos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.CUR_PRO_NOS
     *
     * @param curProNos the value for gm_bm_dorm.CUR_PRO_NOS
     *
     * @mbggenerated
     */
    public void setCurProNos(String curProNos) {
        this.curProNos = curProNos == null ? null : curProNos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.CUR_PRO_NAMES
     *
     * @return the value of gm_bm_dorm.CUR_PRO_NAMES
     *
     * @mbggenerated
     */
    public String getCurProNames() {
        return curProNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.CUR_PRO_NAMES
     *
     * @param curProNames the value for gm_bm_dorm.CUR_PRO_NAMES
     *
     * @mbggenerated
     */
    public void setCurProNames(String curProNames) {
        this.curProNames = curProNames == null ? null : curProNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.CUR_PRO_BEDS
     *
     * @return the value of gm_bm_dorm.CUR_PRO_BEDS
     *
     * @mbggenerated
     */
    public String getCurProBeds() {
        return curProBeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.CUR_PRO_BEDS
     *
     * @param curProBeds the value for gm_bm_dorm.CUR_PRO_BEDS
     *
     * @mbggenerated
     */
    public void setCurProBeds(String curProBeds) {
        this.curProBeds = curProBeds == null ? null : curProBeds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.DAYRENT
     *
     * @return the value of gm_bm_dorm.DAYRENT
     *
     * @mbggenerated
     */
    public float getDayrent() {
        return dayrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.DAYRENT
     *
     * @param dayrent the value for gm_bm_dorm.DAYRENT
     *
     * @mbggenerated
     */
    public void setDayrent(float dayrent) {
        this.dayrent = dayrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.DORM_STATUS
     *
     * @return the value of gm_bm_dorm.DORM_STATUS
     *
     * @mbggenerated
     */
    public Integer getDormStatus() {
        return dormStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.DORM_STATUS
     *
     * @param dormStatus the value for gm_bm_dorm.DORM_STATUS
     *
     * @mbggenerated
     */
    public void setDormStatus(Integer dormStatus) {
        this.dormStatus = dormStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_bm_dorm.REMARKS
     *
     * @return the value of gm_bm_dorm.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_bm_dorm.REMARKS
     *
     * @param remarks the value for gm_bm_dorm.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}