package com.glens.pwCloudOs.materielMg.assetMg.assetType.vo;

import com.glens.eap.platform.core.beans.ValueObject;

public class AssetTypeVo implements ValueObject {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.ASSET_TYPE_CODE
     *
     * @mbggenerated
     */
    private String assetTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.ASSET_TYPE_NAME
     *
     * @mbggenerated
     */
    private String assetTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.ASSET_CLASS_CODE
     *
     * @mbggenerated
     */
    private String assetClassCode;
    
    /**
     * This field corresponds to the database column gm_asset_class.ASSET_CLASS_NAME
     */
    private String assetClassName;
    
    private String assetTypeShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.BRAND
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.MODEL_NO
     *
     * @mbggenerated
     */
    private String modelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.FORMS
     *
     * @mbggenerated
     */
    private String forms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.LIFETIME
     *
     * @mbggenerated
     */
    private Integer lifetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.MEASURE_UNIT
     *
     * @mbggenerated
     */
    private String measureUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.DAILY_RENT
     *
     * @mbggenerated
     */
    private Integer dailyRent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.DAILY_RENT_UNIT
     *
     * @mbggenerated
     */
    private String dailyRentUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.IS_EXATTR
     *
     * @mbggenerated
     */
    private Integer isExattr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_asset_type.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.ASSET_TYPE_CODE
     *
     * @return the value of gm_asset_type.ASSET_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getAssetTypeCode() {
        return assetTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.ASSET_TYPE_CODE
     *
     * @param assetTypeCode the value for gm_asset_type.ASSET_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setAssetTypeCode(String assetTypeCode) {
        this.assetTypeCode = assetTypeCode == null ? null : assetTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.ASSET_TYPE_NAME
     *
     * @return the value of gm_asset_type.ASSET_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getAssetTypeName() {
        return assetTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.ASSET_TYPE_NAME
     *
     * @param assetTypeName the value for gm_asset_type.ASSET_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setAssetTypeName(String assetTypeName) {
        this.assetTypeName = assetTypeName == null ? null : assetTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.ASSET_CLASS_CODE
     *
     * @return the value of gm_asset_type.ASSET_CLASS_CODE
     *
     * @mbggenerated
     */
    public String getAssetClassCode() {
        return assetClassCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.ASSET_CLASS_CODE
     *
     * @param assetClassCode the value for gm_asset_type.ASSET_CLASS_CODE
     *
     * @mbggenerated
     */
    public void setAssetClassCode(String assetClassCode) {
        this.assetClassCode = assetClassCode == null ? null : assetClassCode.trim();
    }

    public String getAssetClassName() {
		return assetClassName;
	}

	public void setAssetClassName(String assetClassName) {
		this.assetClassName = assetClassName;
	}

	public String getAssetTypeShortName() {
		return assetTypeShortName;
	}

	public void setAssetTypeShortName(String assetTypeShortName) {
		this.assetTypeShortName = assetTypeShortName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.BRAND
     *
     * @return the value of gm_asset_type.BRAND
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.BRAND
     *
     * @param brand the value for gm_asset_type.BRAND
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.MODEL_NO
     *
     * @return the value of gm_asset_type.MODEL_NO
     *
     * @mbggenerated
     */
    public String getModelNo() {
        return modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.MODEL_NO
     *
     * @param modelNo the value for gm_asset_type.MODEL_NO
     *
     * @mbggenerated
     */
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo == null ? null : modelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.FORMS
     *
     * @return the value of gm_asset_type.FORMS
     *
     * @mbggenerated
     */
    public String getForms() {
        return forms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.FORMS
     *
     * @param forms the value for gm_asset_type.FORMS
     *
     * @mbggenerated
     */
    public void setForms(String forms) {
        this.forms = forms == null ? null : forms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.LIFETIME
     *
     * @return the value of gm_asset_type.LIFETIME
     *
     * @mbggenerated
     */
    public Integer getLifetime() {
        return lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.LIFETIME
     *
     * @param lifetime the value for gm_asset_type.LIFETIME
     *
     * @mbggenerated
     */
    public void setLifetime(Integer lifetime) {
        this.lifetime = lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.MEASURE_UNIT
     *
     * @return the value of gm_asset_type.MEASURE_UNIT
     *
     * @mbggenerated
     */
    public String getMeasureUnit() {
        return measureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.MEASURE_UNIT
     *
     * @param measureUnit the value for gm_asset_type.MEASURE_UNIT
     *
     * @mbggenerated
     */
    public void setMeasureUnit(String measureUnit) {
        this.measureUnit = measureUnit == null ? null : measureUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.DAILY_RENT
     *
     * @return the value of gm_asset_type.DAILY_RENT
     *
     * @mbggenerated
     */
    public Integer getDailyRent() {
        return dailyRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.DAILY_RENT
     *
     * @param dailyRent the value for gm_asset_type.DAILY_RENT
     *
     * @mbggenerated
     */
    public void setDailyRent(Integer dailyRent) {
        this.dailyRent = dailyRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.DAILY_RENT_UNIT
     *
     * @return the value of gm_asset_type.DAILY_RENT_UNIT
     *
     * @mbggenerated
     */
    public String getDailyRentUnit() {
        return dailyRentUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.DAILY_RENT_UNIT
     *
     * @param dailyRentUnit the value for gm_asset_type.DAILY_RENT_UNIT
     *
     * @mbggenerated
     */
    public void setDailyRentUnit(String dailyRentUnit) {
        this.dailyRentUnit = dailyRentUnit == null ? null : dailyRentUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.IS_EXATTR
     *
     * @return the value of gm_asset_type.IS_EXATTR
     *
     * @mbggenerated
     */
    public Integer getIsExattr() {
        return isExattr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.IS_EXATTR
     *
     * @param isExattr the value for gm_asset_type.IS_EXATTR
     *
     * @mbggenerated
     */
    public void setIsExattr(Integer isExattr) {
        this.isExattr = isExattr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_asset_type.REMARKS
     *
     * @return the value of gm_asset_type.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_asset_type.REMARKS
     *
     * @param remarks the value for gm_asset_type.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}