package com.glens.pwCloudOs.pm.schedulePlan.worklist.web;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import com.glens.eap.platform.core.annotation.ValueObjectProcessor;
import com.glens.eap.platform.core.web.ControllerForm;
@ValueObjectProcessor(clazz="com.glens.pwCloudOs.pm.schedulePlan.worklist.vo.PmWorkList")
public class PmWorkListForm extends ControllerForm {
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;
    private String proName;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORK_DATE
     *
     * @mbggenerated
     */
    private String workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORKER
     *
     * @mbggenerated
     */
    private String worker;
    private String workerName;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORK_TYPE
     *
     * @mbggenerated
     */
    private String workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORKLOAD
     *
     * @mbggenerated
     */
    private Float workload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.WORK_DESCR
     *
     * @mbggenerated
     */
    private String workDescr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.MARKER
     *
     * @mbggenerated
     */
    private String marker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.QUALITY_CHECK_USER
     *
     * @mbggenerated
     */
    private String qualityCheckUser;
    private String qualityCheckUserName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.QUALITY_CHECK_DATE
     *
     * @mbggenerated
     */
    private String qualityCheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.IS_FAULT
     *
     * @mbggenerated
     */
    private Integer isFault = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_list.FAULT_DESCR
     *
     * @mbggenerated
     */
    private String faultDescr;
    
    private String startTime;
    private String endTime;
    

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public Long getRowid() {
		return rowid;
	}

	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	public String getProNo() {
		return proNo;
	}

	public void setProNo(String proNo) {
		this.proNo = proNo;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getWorkDate() {
		return workDate;
	}

	public void setWorkDate(String workDate) {
		this.workDate = workDate;
	}

	public String getWorker() {
		return worker;
	}

	public void setWorker(String worker) {
		this.worker = worker;
	}

	public String getWorkerName() {
		return workerName;
	}

	public void setWorkerName(String workerName) {
		this.workerName = workerName;
	}

	public String getWorkType() {
		return workType;
	}

	public void setWorkType(String workType) {
		this.workType = workType;
	}

	public Float getWorkload() {
		return workload;
	}

	public void setWorkload(Float workload) {
		this.workload = workload;
	}

	public String getWorkDescr() {
		return workDescr;
	}

	public void setWorkDescr(String workDescr) {
		this.workDescr = workDescr;
	}

	public String getMarker() {
		return marker;
	}

	public void setMarker(String marker) {
		this.marker = marker;
	}

	public String getQualityCheckUser() {
		return qualityCheckUser;
	}

	public void setQualityCheckUser(String qualityCheckUser) {
		this.qualityCheckUser = qualityCheckUser;
	}

	public String getQualityCheckUserName() {
		return qualityCheckUserName;
	}

	public void setQualityCheckUserName(String qualityCheckUserName) {
		this.qualityCheckUserName = qualityCheckUserName;
	}

	public String getQualityCheckDate() {
		return qualityCheckDate;
	}

	public void setQualityCheckDate(String qualityCheckDate) {
		this.qualityCheckDate = qualityCheckDate;
	}

	public Integer getIsFault() {
		return isFault;
	}

	public void setIsFault(Integer isFault) {
		this.isFault = isFault;
	}

	public String getFaultDescr() {
		return faultDescr;
	}

	public void setFaultDescr(String faultDescr) {
		this.faultDescr = faultDescr;
	}

	@Override
	protected Map doPreToMap() {
		Map params = new HashMap();
		params.put("proNo", proNo);
		params.put("workDate", workDate);
		params.put("worker", worker);
		params.put("startTime", startTime);
		params.put("endTime", endTime);
		params.put("isFault", isFault);
		return params;
	}

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub

	}

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub
		return null;
	}

}
