package com.glens.pwCloudOs.pm.schedulePlan.worklist.web;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.web.multipart.MultipartFile;

import com.glens.eap.platform.core.annotation.ValueObjectProcessor;
import com.glens.eap.platform.core.web.ControllerForm;
@ValueObjectProcessor(clazz="com.glens.pwCloudOs.pm.schedulePlan.worklist.vo.PmWorkHours")
public class PmWorkHoursForm extends ControllerForm {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;
    private String proName;

    private String categoryCode;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.WORK_DATE
     *
     * @mbggenerated
     */
    private String workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.WORKER
     *
     * @mbggenerated
     */
    private String worker;
    private String workerName;
    private String searchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.WORK_HOURS
     *
     * @mbggenerated
     */
    private Float workHours;
    private Float attendanceHours;
    private Float moreHours;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.IS_PAID_LEAVE
     *
     * @mbggenerated
     */
    private Integer isPaidLeave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.PAID_HOURS
     *
     * @mbggenerated
     */
    private Float paidHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_work_hours.PAID_LEAVE_TYPE
     *
     * @mbggenerated
     */
    private Integer paidLeaveType;
    private Integer hasNotLocal;
    private Integer notLocalStandard;
    private Integer hasMeal;

    private String startTime;
    private String endTime;
    private MultipartFile excelFile;
    private String employeecode;
    private Float pfmCoefficient;
    private Float regulativeHours;
    private String leaveDescr;
    private Integer checkStatus;
    private String checkDescr;
    private String city;
    
    
    public String getSearchName() {
		return searchName;
	}

	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCheckDescr() {
		return checkDescr;
	}

	public void setCheckDescr(String checkDescr) {
		this.checkDescr = checkDescr;
	}

	public Integer getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	public Float getMoreHours() {
		return moreHours;
	}

	public void setMoreHours(Float moreHours) {
		this.moreHours = moreHours;
	}

	public Float getAttendanceHours() {
		return attendanceHours;
	}

	public void setAttendanceHours(Float attendanceHours) {
		this.attendanceHours = attendanceHours;
	}

	public Float getPfmCoefficient() {
		return pfmCoefficient;
	}

	public void setPfmCoefficient(Float pfmCoefficient) {
		this.pfmCoefficient = pfmCoefficient;
	}

	public Float getRegulativeHours() {
		return regulativeHours;
	}

	public void setRegulativeHours(Float regulativeHours) {
		this.regulativeHours = regulativeHours;
	}

	public String getLeaveDescr() {
		return leaveDescr;
	}

	public void setLeaveDescr(String leaveDescr) {
		this.leaveDescr = leaveDescr;
	}

	public String getEmployeecode() {
		return employeecode;
	}

	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	public String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public Integer getNotLocalStandard() {
		return notLocalStandard;
	}

	public void setNotLocalStandard(Integer notLocalStandard) {
		this.notLocalStandard = notLocalStandard;
	}

	public MultipartFile getExcelFile() {
		return excelFile;
	}

	public void setExcelFile(MultipartFile excelFile) {
		this.excelFile = excelFile;
	}

	public Integer getHasNotLocal() {
		return hasNotLocal;
	}

	public void setHasNotLocal(Integer hasNotLocal) {
		this.hasNotLocal = hasNotLocal;
	}

	public Integer getHasMeal() {
		return hasMeal;
	}

	public void setHasMeal(Integer hasMeal) {
		this.hasMeal = hasMeal;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getWorkerName() {
		return workerName;
	}

	public void setWorkerName(String workerName) {
		this.workerName = workerName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.ROWID
     *
     * @return the value of pm_work_hours.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.ROWID
     *
     * @param rowid the value for pm_work_hours.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.PRO_NO
     *
     * @return the value of pm_work_hours.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.PRO_NO
     *
     * @param proNo the value for pm_work_hours.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.WORKER
     *
     * @return the value of pm_work_hours.WORKER
     *
     * @mbggenerated
     */
    public String getWorker() {
        return worker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.WORKER
     *
     * @param worker the value for pm_work_hours.WORKER
     *
     * @mbggenerated
     */
    public void setWorker(String worker) {
        this.worker = worker == null ? null : worker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.WORK_HOURS
     *
     * @return the value of pm_work_hours.WORK_HOURS
     *
     * @mbggenerated
     */
    public Float getWorkHours() {
        return workHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.WORK_HOURS
     *
     * @param workHours the value for pm_work_hours.WORK_HOURS
     *
     * @mbggenerated
     */
    public void setWorkHours(Float workHours) {
        this.workHours = workHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.IS_PAID_LEAVE
     *
     * @return the value of pm_work_hours.IS_PAID_LEAVE
     *
     * @mbggenerated
     */
    public Integer getIsPaidLeave() {
        return isPaidLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.IS_PAID_LEAVE
     *
     * @param isPaidLeave the value for pm_work_hours.IS_PAID_LEAVE
     *
     * @mbggenerated
     */
    public void setIsPaidLeave(Integer isPaidLeave) {
        this.isPaidLeave = isPaidLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.PAID_HOURS
     *
     * @return the value of pm_work_hours.PAID_HOURS
     *
     * @mbggenerated
     */
    public Float getPaidHours() {
        return paidHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.PAID_HOURS
     *
     * @param paidHours the value for pm_work_hours.PAID_HOURS
     *
     * @mbggenerated
     */
    public void setPaidHours(Float paidHours) {
        this.paidHours = paidHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_work_hours.PAID_LEAVE_TYPE
     *
     * @return the value of pm_work_hours.PAID_LEAVE_TYPE
     *
     * @mbggenerated
     */
    public Integer getPaidLeaveType() {
        return paidLeaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_work_hours.PAID_LEAVE_TYPE
     *
     * @param paidLeaveType the value for pm_work_hours.PAID_LEAVE_TYPE
     *
     * @mbggenerated
     */
    public void setPaidLeaveType(Integer paidLeaveType) {
        this.paidLeaveType = paidLeaveType;
    }

   
	public String getWorkDate() {
		return workDate;
	}

	public void setWorkDate(String workDate) {
		this.workDate = workDate;
	}

	@Override
	protected Map doPreToMap() {
		Map params = new HashMap();
		params.put("categoryCode", categoryCode);
		params.put("proNo", proNo);
		params.put("worker", worker);
		params.put("workerName", workerName);
		params.put("searchName", searchName);
		params.put("workDate", workDate);
		params.put("startTime", startTime);
		params.put("endTime", endTime);
		params.put("employeecode", employeecode);
		params.put("checkStatus", checkStatus);
		params.put("checkDescr", checkDescr);
		params.put("areaName", city);
		return params;
	}

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub

	}

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub
		return null;
	}

}
