package com.glens.pwCloudOs.addrLib.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class AddAddrClassVo implements ValueObject{
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.CLASS_CODE
     *
     * @mbggenerated
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.CLASS_NAME
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.CLASS_NAME_SHORT
     *
     * @mbggenerated
     */
    private String classNameShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.LEVEL
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private Date sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_addr_class.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.ROWID
     *
     * @return the value of add_addr_class.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.ROWID
     *
     * @param rowid the value for add_addr_class.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.CLASS_CODE
     *
     * @return the value of add_addr_class.CLASS_CODE
     *
     * @mbggenerated
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.CLASS_CODE
     *
     * @param classCode the value for add_addr_class.CLASS_CODE
     *
     * @mbggenerated
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode == null ? null : classCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.CLASS_NAME
     *
     * @return the value of add_addr_class.CLASS_NAME
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.CLASS_NAME
     *
     * @param className the value for add_addr_class.CLASS_NAME
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.CLASS_NAME_SHORT
     *
     * @return the value of add_addr_class.CLASS_NAME_SHORT
     *
     * @mbggenerated
     */
    public String getClassNameShort() {
        return classNameShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.CLASS_NAME_SHORT
     *
     * @param classNameShort the value for add_addr_class.CLASS_NAME_SHORT
     *
     * @mbggenerated
     */
    public void setClassNameShort(String classNameShort) {
        this.classNameShort = classNameShort == null ? null : classNameShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.LEVEL
     *
     * @return the value of add_addr_class.LEVEL
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.LEVEL
     *
     * @param level the value for add_addr_class.LEVEL
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.SYS_CREATE_TIME
     *
     * @return the value of add_addr_class.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for add_addr_class.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(Date sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.SYS_UPDATE_TIME
     *
     * @return the value of add_addr_class.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for add_addr_class.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(Date sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.SYS_DELETE_TIME
     *
     * @return the value of add_addr_class.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for add_addr_class.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(Date sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.SYS_PROCESS_FLAG
     *
     * @return the value of add_addr_class.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for add_addr_class.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_addr_class.REMARKS
     *
     * @return the value of add_addr_class.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_addr_class.REMARKS
     *
     * @param remarks the value for add_addr_class.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}