package com.glens.pwCloudOs.addrLib.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class AddBaseAddrFieldVo implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.INDUSTRY_CODE
     *
     * @mbggenerated
     */
    private String industryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.E_NAME
     *
     * @mbggenerated
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.C_NAME
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.D_TYPE
     *
     * @mbggenerated
     */
    private Integer dType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.ENUM_SOURCE
     *
     * @mbggenerated
     */
    private Integer enumSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.DIM_LIST
     *
     * @mbggenerated
     */
    private Integer dimList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.DIM_SEARCH
     *
     * @mbggenerated
     */
    private Integer dimSearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.DIM_MAPRENDER
     *
     * @mbggenerated
     */
    private Integer dimMaprender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.DIM_ORDER
     *
     * @mbggenerated
     */
    private Integer dimOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.FIELD_ORDER
     *
     * @mbggenerated
     */
    private Integer fieldOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.OBJ_TYPE_FIELDS
     *
     * @mbggenerated
     */
    private String objTypeFields;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.OBJ_TYPE_SHOW_FIELD
     *
     * @mbggenerated
     */
    private String objTypeShowField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private Date sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_base_addr_field.ENUM_VALUE
     *
     * @mbggenerated
     */
    private String enumValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.ROWID
     *
     * @return the value of add_base_addr_field.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.ROWID
     *
     * @param rowid the value for add_base_addr_field.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.COMPANY_CODE
     *
     * @return the value of add_base_addr_field.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.COMPANY_CODE
     *
     * @param companyCode the value for add_base_addr_field.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.INDUSTRY_CODE
     *
     * @return the value of add_base_addr_field.INDUSTRY_CODE
     *
     * @mbggenerated
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.INDUSTRY_CODE
     *
     * @param industryCode the value for add_base_addr_field.INDUSTRY_CODE
     *
     * @mbggenerated
     */
    public void setIndustryCode(String industryCode) {
        this.industryCode = industryCode == null ? null : industryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.E_NAME
     *
     * @return the value of add_base_addr_field.E_NAME
     *
     * @mbggenerated
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.E_NAME
     *
     * @param eName the value for add_base_addr_field.E_NAME
     *
     * @mbggenerated
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.C_NAME
     *
     * @return the value of add_base_addr_field.C_NAME
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.C_NAME
     *
     * @param cName the value for add_base_addr_field.C_NAME
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.D_TYPE
     *
     * @return the value of add_base_addr_field.D_TYPE
     *
     * @mbggenerated
     */
    public Integer getdType() {
        return dType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.D_TYPE
     *
     * @param dType the value for add_base_addr_field.D_TYPE
     *
     * @mbggenerated
     */
    public void setdType(Integer dType) {
        this.dType = dType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.ENUM_SOURCE
     *
     * @return the value of add_base_addr_field.ENUM_SOURCE
     *
     * @mbggenerated
     */
    public Integer getEnumSource() {
        return enumSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.ENUM_SOURCE
     *
     * @param enumSource the value for add_base_addr_field.ENUM_SOURCE
     *
     * @mbggenerated
     */
    public void setEnumSource(Integer enumSource) {
        this.enumSource = enumSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.DIM_LIST
     *
     * @return the value of add_base_addr_field.DIM_LIST
     *
     * @mbggenerated
     */
    public Integer getDimList() {
        return dimList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.DIM_LIST
     *
     * @param dimList the value for add_base_addr_field.DIM_LIST
     *
     * @mbggenerated
     */
    public void setDimList(Integer dimList) {
        this.dimList = dimList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.DIM_SEARCH
     *
     * @return the value of add_base_addr_field.DIM_SEARCH
     *
     * @mbggenerated
     */
    public Integer getDimSearch() {
        return dimSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.DIM_SEARCH
     *
     * @param dimSearch the value for add_base_addr_field.DIM_SEARCH
     *
     * @mbggenerated
     */
    public void setDimSearch(Integer dimSearch) {
        this.dimSearch = dimSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.DIM_MAPRENDER
     *
     * @return the value of add_base_addr_field.DIM_MAPRENDER
     *
     * @mbggenerated
     */
    public Integer getDimMaprender() {
        return dimMaprender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.DIM_MAPRENDER
     *
     * @param dimMaprender the value for add_base_addr_field.DIM_MAPRENDER
     *
     * @mbggenerated
     */
    public void setDimMaprender(Integer dimMaprender) {
        this.dimMaprender = dimMaprender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.DIM_ORDER
     *
     * @return the value of add_base_addr_field.DIM_ORDER
     *
     * @mbggenerated
     */
    public Integer getDimOrder() {
        return dimOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.DIM_ORDER
     *
     * @param dimOrder the value for add_base_addr_field.DIM_ORDER
     *
     * @mbggenerated
     */
    public void setDimOrder(Integer dimOrder) {
        this.dimOrder = dimOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.FIELD_ORDER
     *
     * @return the value of add_base_addr_field.FIELD_ORDER
     *
     * @mbggenerated
     */
    public Integer getFieldOrder() {
        return fieldOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.FIELD_ORDER
     *
     * @param fieldOrder the value for add_base_addr_field.FIELD_ORDER
     *
     * @mbggenerated
     */
    public void setFieldOrder(Integer fieldOrder) {
        this.fieldOrder = fieldOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.OBJ_TYPE_FIELDS
     *
     * @return the value of add_base_addr_field.OBJ_TYPE_FIELDS
     *
     * @mbggenerated
     */
    public String getObjTypeFields() {
        return objTypeFields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.OBJ_TYPE_FIELDS
     *
     * @param objTypeFields the value for add_base_addr_field.OBJ_TYPE_FIELDS
     *
     * @mbggenerated
     */
    public void setObjTypeFields(String objTypeFields) {
        this.objTypeFields = objTypeFields == null ? null : objTypeFields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.OBJ_TYPE_SHOW_FIELD
     *
     * @return the value of add_base_addr_field.OBJ_TYPE_SHOW_FIELD
     *
     * @mbggenerated
     */
    public String getObjTypeShowField() {
        return objTypeShowField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.OBJ_TYPE_SHOW_FIELD
     *
     * @param objTypeShowField the value for add_base_addr_field.OBJ_TYPE_SHOW_FIELD
     *
     * @mbggenerated
     */
    public void setObjTypeShowField(String objTypeShowField) {
        this.objTypeShowField = objTypeShowField == null ? null : objTypeShowField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.SYS_CREATE_TIME
     *
     * @return the value of add_base_addr_field.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for add_base_addr_field.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(Date sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.SYS_UPDATE_TIME
     *
     * @return the value of add_base_addr_field.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for add_base_addr_field.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(Date sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.SYS_DELETE_TIME
     *
     * @return the value of add_base_addr_field.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public Date getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for add_base_addr_field.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(Date sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.SYS_PROCESS_FLAG
     *
     * @return the value of add_base_addr_field.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for add_base_addr_field.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.REMARKS
     *
     * @return the value of add_base_addr_field.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.REMARKS
     *
     * @param remarks the value for add_base_addr_field.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_base_addr_field.ENUM_VALUE
     *
     * @return the value of add_base_addr_field.ENUM_VALUE
     *
     * @mbggenerated
     */
    public String getEnumValue() {
        return enumValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_base_addr_field.ENUM_VALUE
     *
     * @param enumValue the value for add_base_addr_field.ENUM_VALUE
     *
     * @mbggenerated
     */
    public void setEnumValue(String enumValue) {
        this.enumValue = enumValue == null ? null : enumValue.trim();
    }
}