package com.glens.pwCloudOs.pm.taskMgr.carDispach.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class PmTmVehicleDispatchVo implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.rowid
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.PRO_NAME
     *
     * @mbggenerated
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.ASSET_CODE
     *
     * @mbggenerated
     */
    private String assetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.VEHICLE_NO
     *
     * @mbggenerated
     */
    private String vehicleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.S_PLACE
     *
     * @mbggenerated
     */
    private String sPlace;
    
    private String splaceX;
    
    private String splaceY;
    
   

   
	public String getSplaceX() {
		return splaceX;
	}

	public void setSplaceX(String splaceX) {
		this.splaceX = splaceX;
	}

	public String getSplaceY() {
		return splaceY;
	}

	public void setSplaceY(String splaceY) {
		this.splaceY = splaceY;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.D_PLACE
     *
     * @mbggenerated
     */
    private String dPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.S_MILEAGE
     *
     * @mbggenerated
     */
    private Integer sMileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.D_MILEAGE
     *
     * @mbggenerated
     */
    private Integer dMileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.RIDOR
     *
     * @mbggenerated
     */
    private String ridor;
    
    

   

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.PTJ_DRIVER
     *
     * @mbggenerated
     */
    private String ptjDriver;
    
    private String ptjDriverName;

    public String getPtjDriverName() {
		return ptjDriverName;
	}

	public void setPtjDriverName(String ptjDriverName) {
		this.ptjDriverName = ptjDriverName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.TASK_CODE
     *
     * @mbggenerated
     */
    private String taskCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.TASK_DESC
     *
     * @mbggenerated
     */
    private String taskDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private String sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private String sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private String sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_tm_vehicle_dispatch.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.rowid
     *
     * @return the value of pm_tm_vehicle_dispatch.rowid
     *
     * @mbggenerated
     */
    
    
    private int taskStatus;
    
    public int getTaskStatus() {
		return taskStatus;
	}

	public void setTaskStatus(int taskStatus) {
		this.taskStatus = taskStatus;
	}

	public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.rowid
     *
     * @param rowid the value for pm_tm_vehicle_dispatch.rowid
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.COMPANY_CODE
     *
     * @return the value of pm_tm_vehicle_dispatch.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.COMPANY_CODE
     *
     * @param companyCode the value for pm_tm_vehicle_dispatch.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.PRO_NO
     *
     * @return the value of pm_tm_vehicle_dispatch.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.PRO_NO
     *
     * @param proNo the value for pm_tm_vehicle_dispatch.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.PRO_NAME
     *
     * @return the value of pm_tm_vehicle_dispatch.PRO_NAME
     *
     * @mbggenerated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.PRO_NAME
     *
     * @param proName the value for pm_tm_vehicle_dispatch.PRO_NAME
     *
     * @mbggenerated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.ASSET_CODE
     *
     * @return the value of pm_tm_vehicle_dispatch.ASSET_CODE
     *
     * @mbggenerated
     */
    public String getAssetCode() {
        return assetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.ASSET_CODE
     *
     * @param assetCode the value for pm_tm_vehicle_dispatch.ASSET_CODE
     *
     * @mbggenerated
     */
    public void setAssetCode(String assetCode) {
        this.assetCode = assetCode == null ? null : assetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.VEHICLE_NO
     *
     * @return the value of pm_tm_vehicle_dispatch.VEHICLE_NO
     *
     * @mbggenerated
     */
    public String getVehicleNo() {
        return vehicleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.VEHICLE_NO
     *
     * @param vehicleNo the value for pm_tm_vehicle_dispatch.VEHICLE_NO
     *
     * @mbggenerated
     */
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo == null ? null : vehicleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.S_PLACE
     *
     * @return the value of pm_tm_vehicle_dispatch.S_PLACE
     *
     * @mbggenerated
     */
    public String getSPlace() {
        return sPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.S_PLACE
     *
     * @param sPlace the value for pm_tm_vehicle_dispatch.S_PLACE
     *
     * @mbggenerated
     */
    public void setSPlace(String sPlace) {
        this.sPlace = sPlace == null ? null : sPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.D_PLACE
     *
     * @return the value of pm_tm_vehicle_dispatch.D_PLACE
     *
     * @mbggenerated
     */
    public String getDPlace() {
        return dPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.D_PLACE
     *
     * @param dPlace the value for pm_tm_vehicle_dispatch.D_PLACE
     *
     * @mbggenerated
     */
    public void setDPlace(String dPlace) {
        this.dPlace = dPlace == null ? null : dPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.S_MILEAGE
     *
     * @return the value of pm_tm_vehicle_dispatch.S_MILEAGE
     *
     * @mbggenerated
     */
    public Integer getSMileage() {
        return sMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.S_MILEAGE
     *
     * @param sMileage the value for pm_tm_vehicle_dispatch.S_MILEAGE
     *
     * @mbggenerated
     */
    public void setSMileage(Integer sMileage) {
        this.sMileage = sMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.D_MILEAGE
     *
     * @return the value of pm_tm_vehicle_dispatch.D_MILEAGE
     *
     * @mbggenerated
     */
    public Integer getDMileage() {
        return dMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.D_MILEAGE
     *
     * @param dMileage the value for pm_tm_vehicle_dispatch.D_MILEAGE
     *
     * @mbggenerated
     */
    public void setDMileage(Integer dMileage) {
        this.dMileage = dMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.RIDOR
     *
     * @return the value of pm_tm_vehicle_dispatch.RIDOR
     *
     * @mbggenerated
     */
    public String getRidor() {
        return ridor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.RIDOR
     *
     * @param ridor the value for pm_tm_vehicle_dispatch.RIDOR
     *
     * @mbggenerated
     */
    public void setRidor(String ridor) {
        this.ridor = ridor == null ? null : ridor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.PTJ_DRIVER
     *
     * @return the value of pm_tm_vehicle_dispatch.PTJ_DRIVER
     *
     * @mbggenerated
     */
    public String getPtjDriver() {
        return ptjDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.PTJ_DRIVER
     *
     * @param ptjDriver the value for pm_tm_vehicle_dispatch.PTJ_DRIVER
     *
     * @mbggenerated
     */
    public void setPtjDriver(String ptjDriver) {
        this.ptjDriver = ptjDriver == null ? null : ptjDriver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.TASK_CODE
     *
     * @return the value of pm_tm_vehicle_dispatch.TASK_CODE
     *
     * @mbggenerated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.TASK_CODE
     *
     * @param taskCode the value for pm_tm_vehicle_dispatch.TASK_CODE
     *
     * @mbggenerated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.TASK_DESC
     *
     * @return the value of pm_tm_vehicle_dispatch.TASK_DESC
     *
     * @mbggenerated
     */
    public String getTaskDesc() {
        return taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.TASK_DESC
     *
     * @param taskDesc the value for pm_tm_vehicle_dispatch.TASK_DESC
     *
     * @mbggenerated
     */
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc == null ? null : taskDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.SYS_CREATE_TIME
     *
     * @return the value of pm_tm_vehicle_dispatch.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public String getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for pm_tm_vehicle_dispatch.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(String sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.SYS_UPDATE_TIME
     *
     * @return the value of pm_tm_vehicle_dispatch.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for pm_tm_vehicle_dispatch.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(String sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.SYS_DELETE_TIME
     *
     * @return the value of pm_tm_vehicle_dispatch.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public String getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for pm_tm_vehicle_dispatch.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(String sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.SYS_PROCESS_FLAG
     *
     * @return the value of pm_tm_vehicle_dispatch.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for pm_tm_vehicle_dispatch.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_tm_vehicle_dispatch.REMARKS
     *
     * @return the value of pm_tm_vehicle_dispatch.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_tm_vehicle_dispatch.REMARKS
     *
     * @param remarks the value for pm_tm_vehicle_dispatch.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}