package com.glens.pwCloudOs.pm.baseMgr.pmChange.vo;

import java.util.Date;

public class PmModifyRecordVo {

	private Long rowid;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.PRO_NAME
     *
     * @mbggenerated
     */
    private String proName;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.FIELD_CONTENTS
     *
     * @mbggenerated
     */
    private String fieldContents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.VALUE_CONTENTS
     *
     * @mbggenerated
     */
    private String valueContents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.OPERATETIME
     *
     * @mbggenerated
     */
    private Date operatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.EMPLOYEECODE
     *
     * @mbggenerated
     */
    private String employeecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.ACCOUNT_CODE
     *
     * @mbggenerated
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_modify_record.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    public Long getRowid() {
		return rowid;
	}

	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.COMPANY_CODE
     *
     * @return the value of pm_modify_record.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.COMPANY_CODE
     *
     * @param companyCode the value for pm_modify_record.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.PRO_NO
     *
     * @return the value of pm_modify_record.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.PRO_NO
     *
     * @param proNo the value for pm_modify_record.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.PRO_NAME
     *
     * @return the value of pm_modify_record.PRO_NAME
     *
     * @mbggenerated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.PRO_NAME
     *
     * @param proName the value for pm_modify_record.PRO_NAME
     *
     * @mbggenerated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.FIELD_CONTENTS
     *
     * @return the value of pm_modify_record.FIELD_CONTENTS
     *
     * @mbggenerated
     */
    public String getFieldContents() {
        return fieldContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.FIELD_CONTENTS
     *
     * @param fieldContents the value for pm_modify_record.FIELD_CONTENTS
     *
     * @mbggenerated
     */
    public void setFieldContents(String fieldContents) {
        this.fieldContents = fieldContents == null ? null : fieldContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.VALUE_CONTENTS
     *
     * @return the value of pm_modify_record.VALUE_CONTENTS
     *
     * @mbggenerated
     */
    public String getValueContents() {
        return valueContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.VALUE_CONTENTS
     *
     * @param valueContents the value for pm_modify_record.VALUE_CONTENTS
     *
     * @mbggenerated
     */
    public void setValueContents(String valueContents) {
        this.valueContents = valueContents == null ? null : valueContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.OPERATOR
     *
     * @return the value of pm_modify_record.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.OPERATOR
     *
     * @param operator the value for pm_modify_record.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.OPERATETIME
     *
     * @return the value of pm_modify_record.OPERATETIME
     *
     * @mbggenerated
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.OPERATETIME
     *
     * @param operatetime the value for pm_modify_record.OPERATETIME
     *
     * @mbggenerated
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.EMPLOYEECODE
     *
     * @return the value of pm_modify_record.EMPLOYEECODE
     *
     * @mbggenerated
     */
    public String getEmployeecode() {
        return employeecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.EMPLOYEECODE
     *
     * @param employeecode the value for pm_modify_record.EMPLOYEECODE
     *
     * @mbggenerated
     */
    public void setEmployeecode(String employeecode) {
        this.employeecode = employeecode == null ? null : employeecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.ACCOUNT_CODE
     *
     * @return the value of pm_modify_record.ACCOUNT_CODE
     *
     * @mbggenerated
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.ACCOUNT_CODE
     *
     * @param accountCode the value for pm_modify_record.ACCOUNT_CODE
     *
     * @mbggenerated
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_modify_record.REMARKS
     *
     * @return the value of pm_modify_record.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_modify_record.REMARKS
     *
     * @param remarks the value for pm_modify_record.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}