package com.glens.pwCloudOs.pm.projDoc.vo;

import org.springframework.web.multipart.MultipartFile;

import com.glens.eap.platform.core.beans.ValueObject;

public class ProjDocVo implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.rowid
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.PRO_NO
     *
     * @mbggenerated
     */
    private String proNo;
    private String isChecked;
    private String checkVal;
    private String checkDesc;
    private String remarks1;
    
    private String checkFlag;
    public String getCheckFlag() {
		return checkFlag;
	}

	public void setCheckFlag(String checkFlag) {
		this.checkFlag = checkFlag;
	}

	public String getCheckVal() {
		return checkVal;
	}

	public void setCheckVal(String checkVal) {
		this.checkVal = checkVal;
	}

	public String getCheckDesc() {
		return checkDesc;
	}

	public void setCheckDesc(String checkDesc) {
		this.checkDesc = checkDesc;
	}

	public String getRemarks1() {
		return remarks1;
	}

	public void setRemarks1(String remarks1) {
		this.remarks1 = remarks1;
	}

	public String getIsChecked() {
		return isChecked;
	}

	public void setIsChecked(String isChecked) {
		this.isChecked = isChecked;
	}

	public String getDocNo() {
		return docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

	private String docNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.DOC_TYPELIB_CODE
     *
     * @mbggenerated
     */
    private String docTypelibCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.SUFFIX_NAME
     *
     * @mbggenerated
     */
    private String suffixName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.RE_VISITID
     *
     * @mbggenerated
     */
    private String reVisitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.DL_VISITID
     *
     * @mbggenerated
     */
    private String dlVisitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.UPLOAD_DATE
     *
     * @mbggenerated
     */
    private String uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.FILE_SIZE
     *
     * @mbggenerated
     */
    private Float fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.RE_COUNT
     *
     * @mbggenerated
     */
    private Integer reCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.DL_COUNT
     *
     * @mbggenerated
     */
    private Integer dlCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_document_lib.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;
    
    private String docTypelibName;
    
    private String docClassName;
    
    private String proName;
    
    private String proManager;
    
    private String createTime;
    
    private String accountCode;
    public String getAccountCode() {
		return accountCode;
	}

	public void setAccountCode(String accountCode) {
		this.accountCode = accountCode;
	}

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getProManager() {
		return proManager;
	}

	public void setProManager(String proManager) {
		this.proManager = proManager;
	}

	private MultipartFile projDoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.rowid
     *
     * @return the value of pm_document_lib.rowid
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.rowid
     *
     * @param rowid the value for pm_document_lib.rowid
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.COMPANY_CODE
     *
     * @return the value of pm_document_lib.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.COMPANY_CODE
     *
     * @param companyCode the value for pm_document_lib.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.PRO_NO
     *
     * @return the value of pm_document_lib.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.PRO_NO
     *
     * @param proNo the value for pm_document_lib.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.DOC_TYPELIB_CODE
     *
     * @return the value of pm_document_lib.DOC_TYPELIB_CODE
     *
     * @mbggenerated
     */
    public String getDocTypelibCode() {
        return docTypelibCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.DOC_TYPELIB_CODE
     *
     * @param docTypelibCode the value for pm_document_lib.DOC_TYPELIB_CODE
     *
     * @mbggenerated
     */
    public void setDocTypelibCode(String docTypelibCode) {
        this.docTypelibCode = docTypelibCode == null ? null : docTypelibCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.TITLE
     *
     * @return the value of pm_document_lib.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.TITLE
     *
     * @param title the value for pm_document_lib.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.FILE_NAME
     *
     * @return the value of pm_document_lib.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.FILE_NAME
     *
     * @param fileName the value for pm_document_lib.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.SUFFIX_NAME
     *
     * @return the value of pm_document_lib.SUFFIX_NAME
     *
     * @mbggenerated
     */
    public String getSuffixName() {
        return suffixName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.SUFFIX_NAME
     *
     * @param suffixName the value for pm_document_lib.SUFFIX_NAME
     *
     * @mbggenerated
     */
    public void setSuffixName(String suffixName) {
        this.suffixName = suffixName == null ? null : suffixName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.RE_VISITID
     *
     * @return the value of pm_document_lib.RE_VISITID
     *
     * @mbggenerated
     */
    public String getReVisitid() {
        return reVisitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.RE_VISITID
     *
     * @param reVisitid the value for pm_document_lib.RE_VISITID
     *
     * @mbggenerated
     */
    public void setReVisitid(String reVisitid) {
        this.reVisitid = reVisitid == null ? null : reVisitid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.DL_VISITID
     *
     * @return the value of pm_document_lib.DL_VISITID
     *
     * @mbggenerated
     */
    public String getDlVisitid() {
        return dlVisitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.DL_VISITID
     *
     * @param dlVisitid the value for pm_document_lib.DL_VISITID
     *
     * @mbggenerated
     */
    public void setDlVisitid(String dlVisitid) {
        this.dlVisitid = dlVisitid == null ? null : dlVisitid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.UPLOAD_DATE
     *
     * @return the value of pm_document_lib.UPLOAD_DATE
     *
     * @mbggenerated
     */
    public String getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.UPLOAD_DATE
     *
     * @param uploadDate the value for pm_document_lib.UPLOAD_DATE
     *
     * @mbggenerated
     */
    public void setUploadDate(String uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.FILE_SIZE
     *
     * @return the value of pm_document_lib.FILE_SIZE
     *
     * @mbggenerated
     */
    public Float getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.FILE_SIZE
     *
     * @param fileSize the value for pm_document_lib.FILE_SIZE
     *
     * @mbggenerated
     */
    public void setFileSize(Float fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.RE_COUNT
     *
     * @return the value of pm_document_lib.RE_COUNT
     *
     * @mbggenerated
     */
    public Integer getReCount() {
        return reCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.RE_COUNT
     *
     * @param reCount the value for pm_document_lib.RE_COUNT
     *
     * @mbggenerated
     */
    public void setReCount(Integer reCount) {
        this.reCount = reCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.DL_COUNT
     *
     * @return the value of pm_document_lib.DL_COUNT
     *
     * @mbggenerated
     */
    public Integer getDlCount() {
        return dlCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.DL_COUNT
     *
     * @param dlCount the value for pm_document_lib.DL_COUNT
     *
     * @mbggenerated
     */
    public void setDlCount(Integer dlCount) {
        this.dlCount = dlCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_document_lib.REMARKS
     *
     * @return the value of pm_document_lib.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_document_lib.REMARKS
     *
     * @param remarks the value for pm_document_lib.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	public String getDocTypelibName() {
		return docTypelibName;
	}

	public void setDocTypelibName(String docTypelibName) {
		this.docTypelibName = docTypelibName;
	}

	public String getDocClassName() {
		return docClassName;
	}

	public void setDocClassName(String docClassName) {
		this.docClassName = docClassName;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public MultipartFile getProjDoc() {
		return projDoc;
	}

	public void setProjDoc(MultipartFile projDoc) {
		this.projDoc = projDoc;
	}
}