package com.glens.pwCloudOs.questionnire.vo;

import com.glens.eap.platform.core.beans.ValueObject;

public class QaOption implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.OPTION_CODE
     *
     * @mbggenerated
     */
    private String optionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    private String questionnireCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.QUESTION_CODE
     *
     * @mbggenerated
     */
    private String questionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.OPTION_LABEL
     *
     * @mbggenerated
     */
    private String optionLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.NUM
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.IS_SUPPLEMENT
     *
     * @mbggenerated
     */
    private Integer isSupplement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.OPTION_SCORE
     *
     * @mbggenerated
     */
    private Float optionScore;
    
    private Integer isAnswer;
    private String supplement;
    

    public Integer getIsAnswer() {
		return isAnswer;
	}

	public void setIsAnswer(Integer isAnswer) {
		this.isAnswer = isAnswer;
	}

	public String getSupplement() {
		return supplement;
	}

	public void setSupplement(String supplement) {
		this.supplement = supplement;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_option.ROWID
     *
     * @return the value of qa_option.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_option.ROWID
     *
     * @param rowid the value for qa_option.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_option.OPTION_CODE
     *
     * @return the value of qa_option.OPTION_CODE
     *
     * @mbggenerated
     */
    public String getOptionCode() {
        return optionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_option.OPTION_CODE
     *
     * @param optionCode the value for qa_option.OPTION_CODE
     *
     * @mbggenerated
     */
    public void setOptionCode(String optionCode) {
        this.optionCode = optionCode == null ? null : optionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_option.QUESTIONNIRE_CODE
     *
     * @return the value of qa_option.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    public String getQuestionnireCode() {
        return questionnireCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_option.QUESTIONNIRE_CODE
     *
     * @param questionnireCode the value for qa_option.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    public void setQuestionnireCode(String questionnireCode) {
        this.questionnireCode = questionnireCode == null ? null : questionnireCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_option.QUESTION_CODE
     *
     * @return the value of qa_option.QUESTION_CODE
     *
     * @mbggenerated
     */
    public String getQuestionCode() {
        return questionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_option.QUESTION_CODE
     *
     * @param questionCode the value for qa_option.QUESTION_CODE
     *
     * @mbggenerated
     */
    public void setQuestionCode(String questionCode) {
        this.questionCode = questionCode == null ? null : questionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_option.OPTION_LABEL
     *
     * @return the value of qa_option.OPTION_LABEL
     *
     * @mbggenerated
     */
    public String getOptionLabel() {
        return optionLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_option.OPTION_LABEL
     *
     * @param optionLabel the value for qa_option.OPTION_LABEL
     *
     * @mbggenerated
     */
    public void setOptionLabel(String optionLabel) {
        this.optionLabel = optionLabel == null ? null : optionLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_option.NUM
     *
     * @return the value of qa_option.NUM
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_option.NUM
     *
     * @param num the value for qa_option.NUM
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_option.IS_SUPPLEMENT
     *
     * @return the value of qa_option.IS_SUPPLEMENT
     *
     * @mbggenerated
     */
    public Integer getIsSupplement() {
        return isSupplement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_option.IS_SUPPLEMENT
     *
     * @param isSupplement the value for qa_option.IS_SUPPLEMENT
     *
     * @mbggenerated
     */
    public void setIsSupplement(Integer isSupplement) {
        this.isSupplement = isSupplement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_option.OPTION_SCORE
     *
     * @return the value of qa_option.OPTION_SCORE
     *
     * @mbggenerated
     */
    public Float getOptionScore() {
        return optionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_option.OPTION_SCORE
     *
     * @param optionScore the value for qa_option.OPTION_SCORE
     *
     * @mbggenerated
     */
    public void setOptionScore(Float optionScore) {
        this.optionScore = optionScore;
    }
}