package com.glens.pwCloudOs.questionnire.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class QaQuestionnireSend implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    private String questionnireCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.QUESTION_CODE
     *
     * @mbggenerated
     */
    private String employeeCode;
    private String employeeName;
    private String jobNo;
    private String unitName;
    private String proName;
    private Float score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_option.OPTION_LABEL
     *
     * @mbggenerated
     */
    private Date sendTime;
    
    private int status;
    public String getStatusName(){
    	if(status==0){
    		return "未提交";
    	}else if(status==1){
    		return "已提交";
    	}
    	return "";
    }
    private Date submitTime;

	public Date getSubmitTime() {
		return submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	public Float getScore() {
		return score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	public Long getRowid() {
		return rowid;
	}

	public void setRowid(Long rowid) {
		this.rowid = rowid;
	}

	public String getQuestionnireCode() {
		return questionnireCode;
	}

	public void setQuestionnireCode(String questionnireCode) {
		this.questionnireCode = questionnireCode;
	}

	public String getEmployeeCode() {
		return employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public Date getSendTime() {
		return sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getJobNo() {
		return jobNo;
	}

	public void setJobNo(String jobNo) {
		this.jobNo = jobNo;
	}

}