package com.glens.pwCloudOs.questionnire.vo;

import java.util.Date;
import java.util.List;

import com.glens.eap.platform.core.beans.ValueObject;

public class QaQuestionnire implements ValueObject {
	private List<QaQuestion> questions;
	
    public List<QaQuestion> getQuestions() {
		return questions;
	}

	public void setQuestions(List<QaQuestion> questions) {
		this.questions = questions;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    private String questionnireCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.DESCR
     *
     * @mbggenerated
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.ENABLED_BEGIN_TIME
     *
     * @mbggenerated
     */
    private String enabledBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.ENABLED_END_TIME
     *
     * @mbggenerated
     */
    private String enabledEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.CREATER
     *
     * @mbggenerated
     */
    private String creater;
    private String employeeName;
    private Integer sendedCnt;
    private Integer answerSheetCnt;
    

    public Integer getSendedCnt() {
		return sendedCnt;
	}

	public void setSendedCnt(Integer sendedCnt) {
		this.sendedCnt = sendedCnt;
	}

	public Integer getAnswerSheetCnt() {
		return answerSheetCnt;
	}

	public void setAnswerSheetCnt(Integer answerSheetCnt) {
		this.answerSheetCnt = answerSheetCnt;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_questionnire.TYPE
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.ROWID
     *
     * @return the value of qa_questionnire.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.ROWID
     *
     * @param rowid the value for qa_questionnire.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.QUESTIONNIRE_CODE
     *
     * @return the value of qa_questionnire.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    public String getQuestionnireCode() {
        return questionnireCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.QUESTIONNIRE_CODE
     *
     * @param questionnireCode the value for qa_questionnire.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    public void setQuestionnireCode(String questionnireCode) {
        this.questionnireCode = questionnireCode == null ? null : questionnireCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.TITLE
     *
     * @return the value of qa_questionnire.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.TITLE
     *
     * @param title the value for qa_questionnire.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.DESCR
     *
     * @return the value of qa_questionnire.DESCR
     *
     * @mbggenerated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.DESCR
     *
     * @param descr the value for qa_questionnire.DESCR
     *
     * @mbggenerated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.ENABLED_BEGIN_TIME
     *
     * @return the value of qa_questionnire.ENABLED_BEGIN_TIME
     *
     * @mbggenerated
     */
    public String getEnabledBeginTime() {
        return enabledBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.ENABLED_BEGIN_TIME
     *
     * @param enabledBeginTime the value for qa_questionnire.ENABLED_BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setEnabledBeginTime(String enabledBeginTime) {
        this.enabledBeginTime = enabledBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.ENABLED_END_TIME
     *
     * @return the value of qa_questionnire.ENABLED_END_TIME
     *
     * @mbggenerated
     */
    public String getEnabledEndTime() {
        return enabledEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.ENABLED_END_TIME
     *
     * @param enabledEndTime the value for qa_questionnire.ENABLED_END_TIME
     *
     * @mbggenerated
     */
    public void setEnabledEndTime(String enabledEndTime) {
        this.enabledEndTime = enabledEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.STATUS
     *
     * @return the value of qa_questionnire.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.STATUS
     *
     * @param status the value for qa_questionnire.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.SYS_CREATE_TIME
     *
     * @return the value of qa_questionnire.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for qa_questionnire.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(Date sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.CREATER
     *
     * @return the value of qa_questionnire.CREATER
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.CREATER
     *
     * @param creater the value for qa_questionnire.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_questionnire.TYPE
     *
     * @return the value of qa_questionnire.TYPE
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_questionnire.TYPE
     *
     * @param type the value for qa_questionnire.TYPE
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
    
}