package com.glens.pwCloudOs.questionnire.vo;

import java.util.List;

import com.glens.eap.platform.core.beans.ValueObject;

public class QaQuestion  implements ValueObject{
	private List<QaOption> options;
	
	
    public List<QaOption> getOptions() {
		return options;
	}

	public void setOptions(List<QaOption> options) {
		this.options = options;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.QUESTION_CODE
     *
     * @mbggenerated
     */
    private String questionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    private String questionnireCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.GROUP_CODE
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.SUB_TYPE
     *
     * @mbggenerated
     */
    private String subType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.IDX
     *
     * @mbggenerated
     */
    private Integer idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.NUM
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.RELY_QUESTION_NUM
     *
     * @mbggenerated
     */
    private String relyQuestionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.RELY_OPTION_NUM
     *
     * @mbggenerated
     */
    private String relyOptionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.RELY_RESULT
     *
     * @mbggenerated
     */
    private Integer relyResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.QUESTION_SCORE
     *
     * @mbggenerated
     */
    private Float questionScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qa_question.ANSWER
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.ROWID
     *
     * @return the value of qa_question.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.ROWID
     *
     * @param rowid the value for qa_question.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.QUESTION_CODE
     *
     * @return the value of qa_question.QUESTION_CODE
     *
     * @mbggenerated
     */
    public String getQuestionCode() {
        return questionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.QUESTION_CODE
     *
     * @param questionCode the value for qa_question.QUESTION_CODE
     *
     * @mbggenerated
     */
    public void setQuestionCode(String questionCode) {
        this.questionCode = questionCode == null ? null : questionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.QUESTIONNIRE_CODE
     *
     * @return the value of qa_question.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    public String getQuestionnireCode() {
        return questionnireCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.QUESTIONNIRE_CODE
     *
     * @param questionnireCode the value for qa_question.QUESTIONNIRE_CODE
     *
     * @mbggenerated
     */
    public void setQuestionnireCode(String questionnireCode) {
        this.questionnireCode = questionnireCode == null ? null : questionnireCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.GROUP_CODE
     *
     * @return the value of qa_question.GROUP_CODE
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.GROUP_CODE
     *
     * @param groupCode the value for qa_question.GROUP_CODE
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.TYPE
     *
     * @return the value of qa_question.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.TYPE
     *
     * @param type the value for qa_question.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.SUB_TYPE
     *
     * @return the value of qa_question.SUB_TYPE
     *
     * @mbggenerated
     */
    public String getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.SUB_TYPE
     *
     * @param subType the value for qa_question.SUB_TYPE
     *
     * @mbggenerated
     */
    public void setSubType(String subType) {
        this.subType = subType == null ? null : subType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.TITLE
     *
     * @return the value of qa_question.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.TITLE
     *
     * @param title the value for qa_question.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.IDX
     *
     * @return the value of qa_question.IDX
     *
     * @mbggenerated
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.IDX
     *
     * @param idx the value for qa_question.IDX
     *
     * @mbggenerated
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.NUM
     *
     * @return the value of qa_question.NUM
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.NUM
     *
     * @param num the value for qa_question.NUM
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.RELY_QUESTION_NUM
     *
     * @return the value of qa_question.RELY_QUESTION_NUM
     *
     * @mbggenerated
     */
    public String getRelyQuestionNum() {
        return relyQuestionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.RELY_QUESTION_NUM
     *
     * @param relyQuestionNum the value for qa_question.RELY_QUESTION_NUM
     *
     * @mbggenerated
     */
    public void setRelyQuestionNum(String relyQuestionNum) {
        this.relyQuestionNum = relyQuestionNum == null ? null : relyQuestionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.RELY_OPTION_NUM
     *
     * @return the value of qa_question.RELY_OPTION_NUM
     *
     * @mbggenerated
     */
    public String getRelyOptionNum() {
        return relyOptionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.RELY_OPTION_NUM
     *
     * @param relyOptionNum the value for qa_question.RELY_OPTION_NUM
     *
     * @mbggenerated
     */
    public void setRelyOptionNum(String relyOptionNum) {
        this.relyOptionNum = relyOptionNum == null ? null : relyOptionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.RELY_RESULT
     *
     * @return the value of qa_question.RELY_RESULT
     *
     * @mbggenerated
     */
    public Integer getRelyResult() {
        return relyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.RELY_RESULT
     *
     * @param relyResult the value for qa_question.RELY_RESULT
     *
     * @mbggenerated
     */
    public void setRelyResult(Integer relyResult) {
        this.relyResult = relyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.QUESTION_SCORE
     *
     * @return the value of qa_question.QUESTION_SCORE
     *
     * @mbggenerated
     */
    public Float getQuestionScore() {
        return questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.QUESTION_SCORE
     *
     * @param questionScore the value for qa_question.QUESTION_SCORE
     *
     * @mbggenerated
     */
    public void setQuestionScore(Float questionScore) {
        this.questionScore = questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qa_question.ANSWER
     *
     * @return the value of qa_question.ANSWER
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qa_question.ANSWER
     *
     * @param answer the value for qa_question.ANSWER
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}