package com.glens.pwCloudOs.pm.everydayMgr.consumableReceive.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class GmMaterialUse implements ValueObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.rowid
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.MATERIAL_BATCHNO
     *
     * @mbggenerated
     */
    private String materialBatchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.LOAN_EMPLOYEECODE
     *
     * @mbggenerated
     */
    private String loanEmployeecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.LOAN_EMPLOYEENAME
     *
     * @mbggenerated
     */
    private String loanEmployeename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.LOAN_UNIT_CODE
     *
     * @mbggenerated
     */
    private String loanUnitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.LOAN_UNIT_NAME
     *
     * @mbggenerated
     */
    private String loanUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.LOAN_PRO_NO
     *
     * @mbggenerated
     */
    private String loanProNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.LOAN_PRO_NAME
     *
     * @mbggenerated
     */
    private String loanProName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.USE_COUNT
     *
     * @mbggenerated
     */
    private Integer useCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.USE_DATE
     *
     * @mbggenerated
     */
    private String useDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.USE_DESC
     *
     * @mbggenerated
     */
    private String useDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.FLOW_STATUS
     *
     * @mbggenerated
     */
    private Integer flowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    private String sysCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    private String sysUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    private String sysDeleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    private String sysProcessFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_material_use.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;
    private String materialName;
    private String type;
    private String loanEmployeename2;
    private String loanEmployeecode2;
    private String assetTypeName;
    private String brand;
    private String modelNo;
    
    public String getAssetTypeName() {
		return assetTypeName;
	}

	public void setAssetTypeName(String assetTypeName) {
		this.assetTypeName = assetTypeName;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModelNo() {
		return modelNo;
	}

	public void setModelNo(String modelNo) {
		this.modelNo = modelNo;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLoanEmployeename2() {
		return loanEmployeename2;
	}

	public void setLoanEmployeename2(String loanEmployeename2) {
		this.loanEmployeename2 = loanEmployeename2;
	}

	public String getLoanEmployeecode2() {
		return loanEmployeecode2;
	}

	public void setLoanEmployeecode2(String loanEmployeecode2) {
		this.loanEmployeecode2 = loanEmployeecode2;
	}

	public String getMaterialName() {
		return materialName;
	}

	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.rowid
     *
     * @return the value of gm_material_use.rowid
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.rowid
     *
     * @param rowid the value for gm_material_use.rowid
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.MATERIAL_BATCHNO
     *
     * @return the value of gm_material_use.MATERIAL_BATCHNO
     *
     * @mbggenerated
     */
    public String getMaterialBatchno() {
        return materialBatchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.MATERIAL_BATCHNO
     *
     * @param materialBatchno the value for gm_material_use.MATERIAL_BATCHNO
     *
     * @mbggenerated
     */
    public void setMaterialBatchno(String materialBatchno) {
        this.materialBatchno = materialBatchno == null ? null : materialBatchno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.LOAN_EMPLOYEECODE
     *
     * @return the value of gm_material_use.LOAN_EMPLOYEECODE
     *
     * @mbggenerated
     */
    public String getLoanEmployeecode() {
        return loanEmployeecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.LOAN_EMPLOYEECODE
     *
     * @param loanEmployeecode the value for gm_material_use.LOAN_EMPLOYEECODE
     *
     * @mbggenerated
     */
    public void setLoanEmployeecode(String loanEmployeecode) {
        this.loanEmployeecode = loanEmployeecode == null ? null : loanEmployeecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.LOAN_EMPLOYEENAME
     *
     * @return the value of gm_material_use.LOAN_EMPLOYEENAME
     *
     * @mbggenerated
     */
    public String getLoanEmployeename() {
        return loanEmployeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.LOAN_EMPLOYEENAME
     *
     * @param loanEmployeename the value for gm_material_use.LOAN_EMPLOYEENAME
     *
     * @mbggenerated
     */
    public void setLoanEmployeename(String loanEmployeename) {
        this.loanEmployeename = loanEmployeename == null ? null : loanEmployeename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.LOAN_UNIT_CODE
     *
     * @return the value of gm_material_use.LOAN_UNIT_CODE
     *
     * @mbggenerated
     */
    public String getLoanUnitCode() {
        return loanUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.LOAN_UNIT_CODE
     *
     * @param loanUnitCode the value for gm_material_use.LOAN_UNIT_CODE
     *
     * @mbggenerated
     */
    public void setLoanUnitCode(String loanUnitCode) {
        this.loanUnitCode = loanUnitCode == null ? null : loanUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.LOAN_UNIT_NAME
     *
     * @return the value of gm_material_use.LOAN_UNIT_NAME
     *
     * @mbggenerated
     */
    public String getLoanUnitName() {
        return loanUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.LOAN_UNIT_NAME
     *
     * @param loanUnitName the value for gm_material_use.LOAN_UNIT_NAME
     *
     * @mbggenerated
     */
    public void setLoanUnitName(String loanUnitName) {
        this.loanUnitName = loanUnitName == null ? null : loanUnitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.LOAN_PRO_NO
     *
     * @return the value of gm_material_use.LOAN_PRO_NO
     *
     * @mbggenerated
     */
    public String getLoanProNo() {
        return loanProNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.LOAN_PRO_NO
     *
     * @param loanProNo the value for gm_material_use.LOAN_PRO_NO
     *
     * @mbggenerated
     */
    public void setLoanProNo(String loanProNo) {
        this.loanProNo = loanProNo == null ? null : loanProNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.LOAN_PRO_NAME
     *
     * @return the value of gm_material_use.LOAN_PRO_NAME
     *
     * @mbggenerated
     */
    public String getLoanProName() {
        return loanProName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.LOAN_PRO_NAME
     *
     * @param loanProName the value for gm_material_use.LOAN_PRO_NAME
     *
     * @mbggenerated
     */
    public void setLoanProName(String loanProName) {
        this.loanProName = loanProName == null ? null : loanProName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.USE_COUNT
     *
     * @return the value of gm_material_use.USE_COUNT
     *
     * @mbggenerated
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.USE_COUNT
     *
     * @param useCount the value for gm_material_use.USE_COUNT
     *
     * @mbggenerated
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.USE_DATE
     *
     * @return the value of gm_material_use.USE_DATE
     *
     * @mbggenerated
     */
    public String getUseDate() {
        return useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.USE_DATE
     *
     * @param useDate the value for gm_material_use.USE_DATE
     *
     * @mbggenerated
     */
    public void setUseDate(String useDate) {
        this.useDate = useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.USE_DESC
     *
     * @return the value of gm_material_use.USE_DESC
     *
     * @mbggenerated
     */
    public String getUseDesc() {
        return useDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.USE_DESC
     *
     * @param useDesc the value for gm_material_use.USE_DESC
     *
     * @mbggenerated
     */
    public void setUseDesc(String useDesc) {
        this.useDesc = useDesc == null ? null : useDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.FLOW_STATUS
     *
     * @return the value of gm_material_use.FLOW_STATUS
     *
     * @mbggenerated
     */
    public Integer getFlowStatus() {
        return flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.FLOW_STATUS
     *
     * @param flowStatus the value for gm_material_use.FLOW_STATUS
     *
     * @mbggenerated
     */
    public void setFlowStatus(Integer flowStatus) {
        this.flowStatus = flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.SYS_CREATE_TIME
     *
     * @return the value of gm_material_use.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public String getSysCreateTime() {
        return sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.SYS_CREATE_TIME
     *
     * @param sysCreateTime the value for gm_material_use.SYS_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setSysCreateTime(String sysCreateTime) {
        this.sysCreateTime = sysCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.SYS_UPDATE_TIME
     *
     * @return the value of gm_material_use.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getSysUpdateTime() {
        return sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.SYS_UPDATE_TIME
     *
     * @param sysUpdateTime the value for gm_material_use.SYS_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSysUpdateTime(String sysUpdateTime) {
        this.sysUpdateTime = sysUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.SYS_DELETE_TIME
     *
     * @return the value of gm_material_use.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public String getSysDeleteTime() {
        return sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.SYS_DELETE_TIME
     *
     * @param sysDeleteTime the value for gm_material_use.SYS_DELETE_TIME
     *
     * @mbggenerated
     */
    public void setSysDeleteTime(String sysDeleteTime) {
        this.sysDeleteTime = sysDeleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.SYS_PROCESS_FLAG
     *
     * @return the value of gm_material_use.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public String getSysProcessFlag() {
        return sysProcessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.SYS_PROCESS_FLAG
     *
     * @param sysProcessFlag the value for gm_material_use.SYS_PROCESS_FLAG
     *
     * @mbggenerated
     */
    public void setSysProcessFlag(String sysProcessFlag) {
        this.sysProcessFlag = sysProcessFlag == null ? null : sysProcessFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_material_use.REMARKS
     *
     * @return the value of gm_material_use.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_material_use.REMARKS
     *
     * @param remarks the value for gm_material_use.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}