package com.glens.pwCloudOs.gm.vm.filling.vo;

import com.glens.eap.platform.core.beans.ValueObject;


public class GmVmSinopecBill implements ValueObject  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.ROWID
     *
     * @mbggenerated
     */
    private Long rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.CARD_NO
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.REC_TIME
     *
     * @mbggenerated
     */
    private String recTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.OIL_CATEGORY
     *
     * @mbggenerated
     */
    private String oilCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.COUNT
     *
     * @mbggenerated
     */
    private Float count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.PRICE
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.AMOUNT
     *
     * @mbggenerated
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.SCORE
     *
     * @mbggenerated
     */
    private Float score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.BALANCE
     *
     * @mbggenerated
     */
    private Float balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.CHECK_TIME
     *
     * @mbggenerated
     */
    private String checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.CHECK_RESULT
     *
     * @mbggenerated
     */
    private Integer checkResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gm_vm_sinopec_bill.REL_ID
     *
     * @mbggenerated
     */
    private Long relId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.ROWID
     *
     * @return the value of gm_vm_sinopec_bill.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.ROWID
     *
     * @param rowid the value for gm_vm_sinopec_bill.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.CARD_NO
     *
     * @return the value of gm_vm_sinopec_bill.CARD_NO
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.CARD_NO
     *
     * @param cardNo the value for gm_vm_sinopec_bill.CARD_NO
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.REC_TIME
     *
     * @return the value of gm_vm_sinopec_bill.REC_TIME
     *
     * @mbggenerated
     */
    public String getRecTime() {
        return recTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.REC_TIME
     *
     * @param recTime the value for gm_vm_sinopec_bill.REC_TIME
     *
     * @mbggenerated
     */
    public void setRecTime(String recTime) {
        this.recTime = recTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.OIL_CATEGORY
     *
     * @return the value of gm_vm_sinopec_bill.OIL_CATEGORY
     *
     * @mbggenerated
     */
    public String getOilCategory() {
        return oilCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.OIL_CATEGORY
     *
     * @param oilCategory the value for gm_vm_sinopec_bill.OIL_CATEGORY
     *
     * @mbggenerated
     */
    public void setOilCategory(String oilCategory) {
        this.oilCategory = oilCategory == null ? null : oilCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.COUNT
     *
     * @return the value of gm_vm_sinopec_bill.COUNT
     *
     * @mbggenerated
     */
    public Float getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.COUNT
     *
     * @param count the value for gm_vm_sinopec_bill.COUNT
     *
     * @mbggenerated
     */
    public void setCount(Float count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.PRICE
     *
     * @return the value of gm_vm_sinopec_bill.PRICE
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.PRICE
     *
     * @param price the value for gm_vm_sinopec_bill.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.AMOUNT
     *
     * @return the value of gm_vm_sinopec_bill.AMOUNT
     *
     * @mbggenerated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.AMOUNT
     *
     * @param amount the value for gm_vm_sinopec_bill.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.SCORE
     *
     * @return the value of gm_vm_sinopec_bill.SCORE
     *
     * @mbggenerated
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.SCORE
     *
     * @param score the value for gm_vm_sinopec_bill.SCORE
     *
     * @mbggenerated
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.BALANCE
     *
     * @return the value of gm_vm_sinopec_bill.BALANCE
     *
     * @mbggenerated
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.BALANCE
     *
     * @param balance the value for gm_vm_sinopec_bill.BALANCE
     *
     * @mbggenerated
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.ADDRESS
     *
     * @return the value of gm_vm_sinopec_bill.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.ADDRESS
     *
     * @param address the value for gm_vm_sinopec_bill.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.CHECK_TIME
     *
     * @return the value of gm_vm_sinopec_bill.CHECK_TIME
     *
     * @mbggenerated
     */
    public String getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.CHECK_TIME
     *
     * @param checkTime the value for gm_vm_sinopec_bill.CHECK_TIME
     *
     * @mbggenerated
     */
    public void setCheckTime(String checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.CHECK_RESULT
     *
     * @return the value of gm_vm_sinopec_bill.CHECK_RESULT
     *
     * @mbggenerated
     */
    public Integer getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.CHECK_RESULT
     *
     * @param checkResult the value for gm_vm_sinopec_bill.CHECK_RESULT
     *
     * @mbggenerated
     */
    public void setCheckResult(Integer checkResult) {
        this.checkResult = checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_sinopec_bill.REL_ID
     *
     * @return the value of gm_vm_sinopec_bill.REL_ID
     *
     * @mbggenerated
     */
    public Long getRelId() {
        return relId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_sinopec_bill.REL_ID
     *
     * @param relId the value for gm_vm_sinopec_bill.REL_ID
     *
     * @mbggenerated
     */
    public void setRelId(Long relId) {
        this.relId = relId;
    }
}