package com.glens.pwCloudOs.gm.vm.filling.web;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.web.multipart.MultipartFile;

import com.glens.eap.platform.core.annotation.ValueObjectProcessor;
import com.glens.eap.platform.core.web.ControllerForm;

@ValueObjectProcessor(clazz="com.glens.pwCloudOs.gm.vm.filling.vo.GmVmFillingRecord")
public class GmVmFillingRecordForm extends ControllerForm {
	private String proName;
	private String deptName;
	private String vehicleUserName;
	private MultipartFile excelFile;
    private Long rowid;
    private String companyCode;
    private Integer useType;
    private String proNo;
    private String deptNo;
    private Integer payType;
    private String cardNo;
    private String plateNo;
    private Float amount;
    private String place;
    private String vehicleUser;
    private String fillingTime;
    private String remarks;
    private String createTime;
    private String pics;
    private String imgs;
    private Integer checkResult;
    
    
    
    public Integer getCheckResult() {
		return checkResult;
	}

	public void setCheckResult(Integer checkResult) {
		this.checkResult = checkResult;
	}

	public String getImgs() {
		return imgs;
	}

	public void setImgs(String imgs) {
		this.imgs = imgs;
	}

	public String getPics() {
		return pics;
	}

	public void setPics(String pics) {
		this.pics = pics;
	}

	public MultipartFile getExcelFile() {
		return excelFile;
	}

	public void setExcelFile(MultipartFile excelFile) {
		this.excelFile = excelFile;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getVehicleUserName() {
		return vehicleUserName;
	}

	public void setVehicleUserName(String vehicleUserName) {
		this.vehicleUserName = vehicleUserName;
	} 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.ROWID
     *
     * @return the value of gm_vm_filling_record.ROWID
     *
     * @mbggenerated
     */
    public Long getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.ROWID
     *
     * @param rowid the value for gm_vm_filling_record.ROWID
     *
     * @mbggenerated
     */
    public void setRowid(Long rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.COMPANY_CODE
     *
     * @return the value of gm_vm_filling_record.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.COMPANY_CODE
     *
     * @param companyCode the value for gm_vm_filling_record.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.USE_TYPE
     *
     * @return the value of gm_vm_filling_record.USE_TYPE
     *
     * @mbggenerated
     */
    public Integer getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.USE_TYPE
     *
     * @param useType the value for gm_vm_filling_record.USE_TYPE
     *
     * @mbggenerated
     */
    public void setUseType(Integer useType) {
        this.useType = useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.PRO_NO
     *
     * @return the value of gm_vm_filling_record.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.PRO_NO
     *
     * @param proNo the value for gm_vm_filling_record.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.DEPT_NO
     *
     * @return the value of gm_vm_filling_record.DEPT_NO
     *
     * @mbggenerated
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.DEPT_NO
     *
     * @param deptNo the value for gm_vm_filling_record.DEPT_NO
     *
     * @mbggenerated
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo == null ? null : deptNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.PAY_TYPE
     *
     * @return the value of gm_vm_filling_record.PAY_TYPE
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.PAY_TYPE
     *
     * @param payType the value for gm_vm_filling_record.PAY_TYPE
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.CARD_NO
     *
     * @return the value of gm_vm_filling_record.CARD_NO
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.CARD_NO
     *
     * @param cardNo the value for gm_vm_filling_record.CARD_NO
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.PLATE_NO
     *
     * @return the value of gm_vm_filling_record.PLATE_NO
     *
     * @mbggenerated
     */
    public String getPlateNo() {
        return plateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.PLATE_NO
     *
     * @param plateNo the value for gm_vm_filling_record.PLATE_NO
     *
     * @mbggenerated
     */
    public void setPlateNo(String plateNo) {
        this.plateNo = plateNo == null ? null : plateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.AMOUNT
     *
     * @return the value of gm_vm_filling_record.AMOUNT
     *
     * @mbggenerated
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.AMOUNT
     *
     * @param amount the value for gm_vm_filling_record.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.PLACE
     *
     * @return the value of gm_vm_filling_record.PLACE
     *
     * @mbggenerated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.PLACE
     *
     * @param place the value for gm_vm_filling_record.PLACE
     *
     * @mbggenerated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.VEHICLE_USER
     *
     * @return the value of gm_vm_filling_record.VEHICLE_USER
     *
     * @mbggenerated
     */
    public String getVehicleUser() {
        return vehicleUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.VEHICLE_USER
     *
     * @param vehicleUser the value for gm_vm_filling_record.VEHICLE_USER
     *
     * @mbggenerated
     */
    public void setVehicleUser(String vehicleUser) {
        this.vehicleUser = vehicleUser == null ? null : vehicleUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.FILLING_TIME
     *
     * @return the value of gm_vm_filling_record.FILLING_TIME
     *
     * @mbggenerated
     */
    public String getFillingTime() {
        return fillingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.FILLING_TIME
     *
     * @param fillingTime the value for gm_vm_filling_record.FILLING_TIME
     *
     * @mbggenerated
     */
    public void setFillingTime(String fillingTime) {
        this.fillingTime = fillingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.REMARKS
     *
     * @return the value of gm_vm_filling_record.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.REMARKS
     *
     * @param remarks the value for gm_vm_filling_record.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gm_vm_filling_record.CREATE_TIME
     *
     * @return the value of gm_vm_filling_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gm_vm_filling_record.CREATE_TIME
     *
     * @param createTime the value for gm_vm_filling_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
    private String startTime;
    private String endTime;
    
	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Override
	protected Map doPreToMap() {
		Map params = new HashMap();
		params.put("companyCode", companyCode);
		params.put("useType", useType);
		params.put("proNo", proNo);
		params.put("deptNo", deptNo);
		params.put("payType", payType);
		params.put("cardNo", cardNo);
		params.put("plateNo", plateNo);
		params.put("vehicleUser", vehicleUser);
		params.put("startTime", startTime);
		params.put("endTime", endTime);
		if(checkResult!=null && checkResult!=-1){
			params.put("checkResult", checkResult);
		}
		return params;
	}

	@Override
	protected void doPostRequest(HttpServletRequest request) {
		// TODO Auto-generated method stub

	}

	@Override
	public Object getGenerateKey() {
		// TODO Auto-generated method stub
		return null;
	}

}
