package com.glens.pwCloudOs.pm.schedulePlan.qualityDaily.vo;

import java.util.Date;

import com.glens.eap.platform.core.beans.ValueObject;

public class PmDayQcVo implements ValueObject {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_day_qc.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;
    private String proNo;
    private String proName;
    private String reportDate;
    private String remarks;
    private String proManager;
    private String reportStatus;
    private String station;
    private String line;
    private String cablepit;
    private String checkTypeCode;
    private String checkTypeName;
    private String deviceLperson;
    private String checkName;
    private String checkDate;
    private int checkResult;
	private String problemP1;
    private String problemP2;
    private String problemP3;
    private String problemTypeCode;
    private String problemTypeName;
	private String problemDesc;
    private int  rectifyStatus;
    private String rectifyDate;
    private String rectifyDesc;
    private String unitWorkload;
    private String categoryName;
    
    private String fromDate;
    private String toDate;
    
    private String qcNum;
    
    private String proPhase;
    private String checkClassCode;
    private String neiye;
    private String waiye;
    
    private String proStatus;
    
    
    public String getProStatus() {
		return proStatus;
	}

	public void setProStatus(String proStatus) {
		this.proStatus = proStatus;
	}

	public String getNeiye() {
		return neiye;
	}

	public void setNeiye(String neiye) {
		this.neiye = neiye;
	}

	public String getWaiye() {
		return waiye;
	}

	public void setWaiye(String waiye) {
		this.waiye = waiye;
	}

	public String getCheckClassCode() {
		return checkClassCode;
	}

	public void setCheckClassCode(String checkClassCode) {
		this.checkClassCode = checkClassCode;
	}

	public String getProPhase() {
		return proPhase;
	}

	public void setProPhase(String proPhase) {
		this.proPhase = proPhase;
	}

	public String getQcNum() {
		return qcNum;
	}

	public void setQcNum(String qcNum) {
		this.qcNum = qcNum;
	}

	public String getFromDate() {
		return fromDate;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public String getToDate() {
		return toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	private String categoryCode; //类别代码
    private String employeeCode;
    
    
  
    public String getEmployeeCode() {
		return employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getProblemTypeName() {
		return problemTypeName;
	}

	public void setProblemTypeName(String problemTypeName) {
		this.problemTypeName = problemTypeName;
	}
    public String getCheckTypeName() {
		return checkTypeName;
	}

	public void setCheckTypeName(String checkTypeName) {
		this.checkTypeName = checkTypeName;
	}
    
    public String getUnitWorkload() {
		return unitWorkload;
	}

	public void setUnitWorkload(String unitWorkload) {
		this.unitWorkload = unitWorkload;
	}

	public String getStation() {
		return station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getLine() {
		return line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	public String getCablepit() {
		return cablepit;
	}

	public void setCablepit(String cablepit) {
		this.cablepit = cablepit;
	}

	public String getCheckTypeCode() {
		return checkTypeCode;
	}

	public void setCheckTypeCode(String checkTypeCode) {
		this.checkTypeCode = checkTypeCode;
	}

	public String getDeviceLperson() {
		return deviceLperson;
	}

	public void setDeviceLperson(String deviceLperson) {
		this.deviceLperson = deviceLperson;
	}

	public String getCheckName() {
		return checkName;
	}

	public void setCheckName(String checkName) {
		this.checkName = checkName;
	}

	public String getCheckDate() {
		return checkDate;
	}

	public void setCheckDate(String checkDate) {
		this.checkDate = checkDate;
	}

	public int getCheckResult() {
		return checkResult;
	}

	public void setCheckResult(int checkResult) {
		this.checkResult = checkResult;
	}

	public String getProblemP1() {
		return problemP1;
	}

	public void setProblemP1(String problemP1) {
		this.problemP1 = problemP1;
	}

	public String getProblemP2() {
		return problemP2;
	}

	public void setProblemP2(String problemP2) {
		this.problemP2 = problemP2;
	}

	public String getProblemP3() {
		return problemP3;
	}

	public void setProblemP3(String problemP3) {
		this.problemP3 = problemP3;
	}

	public String getProblemTypeCode() {
		return problemTypeCode;
	}

	public void setProblemTypeCode(String problemTypeCode) {
		this.problemTypeCode = problemTypeCode;
	}

	public String getProblemDesc() {
		return problemDesc;
	}

	public void setProblemDesc(String problemDesc) {
		this.problemDesc = problemDesc;
	}

	public int getRectifyStatus() {
		return rectifyStatus;
	}

	public void setRectifyStatus(int rectifyStatus) {
		this.rectifyStatus = rectifyStatus;
	}

	public String getRectifyDate() {
		return rectifyDate;
	}

	public void setRectifyDate(String rectifyDate) {
		this.rectifyDate = rectifyDate;
	}

	public String getRectifyDesc() {
		return rectifyDesc;
	}

	public void setRectifyDesc(String rectifyDesc) {
		this.rectifyDesc = rectifyDesc;
	}

	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_qc.COMPANY_CODE
     *
     * @return the value of pm_day_qc.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_qc.COMPANY_CODE
     *
     * @param companyCode the value for pm_day_qc.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_qc.PRO_NO
     *
     * @return the value of pm_day_qc.PRO_NO
     *
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_qc.PRO_NO
     *
     * @param proNo the value for pm_day_qc.PRO_NO
     *
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_qc.PRO_NAME
     *
     * @return the value of pm_day_qc.PRO_NAME
     *
     * @mbggenerated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_qc.PRO_NAME
     *
     * @param proName the value for pm_day_qc.PRO_NAME
     *
     * @mbggenerated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_qc.REPORT_DATE
     *
     * @return the value of pm_day_qc.REPORT_DATE
     *
     * @mbggenerated
     */
    public String getReportDate() {
        return reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_qc.REPORT_DATE
     *
     * @param reportDate the value for pm_day_qc.REPORT_DATE
     *
     * @mbggenerated
     */
    public void setReportDate(String reportDate) {
        this.reportDate = reportDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_day_qc.REMARKS
     *
     * @return the value of pm_day_qc.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_day_qc.REMARKS
     *
     * @param remarks the value for pm_day_qc.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

	

	public String getProManager() {
		return proManager;
	}

	public void setProManager(String proManager) {
		this.proManager = proManager;
	}

	public String getReportStatus() {
		return reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}
}